### PR TITLE
Make seal last and move newing up create map functions before do config and seal.

### PR DESCRIPTION
**Pull request by TylerCarlson1**
Issue with AutoMapper.Collection it's going to need to call IConfiguration.ResolveTypeMap which is done on seal now.  The problem is the thing gets sealed without the functions to actively run ResolveTypeMaps,  therefore I get exceptions.

### CODE REVIEW

**Comment by TylerCarlson1** [comment]
Looks like the Auto-Build is stuck downloading. :(

**Comment by jbogard** [comment]
Conflicts :(

**Comment by TylerCarlson1** [comment]
nooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Ok I'll fix

**Comment by TylerCarlson1** [comment]
Done Just wait for build again :(

**Comment by TylerCarlson1** [comment]
Fixed my problem.  AM.Collections is compatible with 5.0 now.  Question is can you make a nuget package depend on another package in a myget feed?  And if so is it going to be super confusing?  Can't depend on beta1 right now cause it won't work. :(

**Comment by jbogard** [comment]
Ah. Nuts.

**Comment by TylerCarlson1** [comment]
Yea sorry about that.  I wait until AutoMapper is in some form of release before trying to integrate into my applications, and I always run into problems when I do.

**Comment by TylerCarlson1** [comment]
Soooooo  Any idea when 5.0 Beta 2 or 5.0 release will be available on NuGet?

**Comment by jbogard** [comment]
5.0 can't be released until .Net Core RTM's

**Pull request merged**
