### PR TITLE
ExpressionMapping assemblies with sample AdventureWorks tiered solution.

### PR DESCRIPTION
**Pull request by BlaiseD**
I've created a pull request with actual files you can merge this time.  The changes allow:
1) Mapping of IQueryable expressions Expression<Func<IQueryable<UserModel>, IQueryable<UserModel>>> exp; to Expression<Func<IQueryable<User>, IQueryable<User>>> exp;.
2) Because of 1), provides an alternative to using Project().To().

It includes sample projects for AdventureWorks 2008R2.  Sorry for the confusion.

Thanks.

### CODE REVIEW

**Comment by jbogard** [comment]
Hm so this is like an add-on project? Would you want this to be folded in to the core project?

**Comment by BlaiseD** [comment]
Sorry - missed your comment from May 7.  I wanted to make it part of AutoMapper - your call on moving it to the core project.  I thought the separate project would make it easier to merge.

**Comment by jbogard** [comment]
Yeah, I'm on board with that. As long as I'm not adding dependencies, I'm good.

**Comment by BlaiseD** [comment]
Got it.  So the references to EF 6 will have to go.  I'll let you know when it is ready.


________________________________

**Comment by jbogard** [comment]
Not necessarily - I created the AutoMapper.EF6 package for EF-specific extensions. But there are likely things here that are EF-agnostic and EF-specific?

**Comment by BlaiseD** [comment]
The expression mapping is EF agnostic.  The sample persistence code uses EF.  I suppose we can close this now? There's way too much overlap with @TylerCarlson1 's work.  Different design but I believe he's got it covered.

**Comment by jbogard** [comment]
Okeydokey, closed. Thanks!!

**Pull request closed without merging**
