### PR TITLE
Bugfix #1727

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by jbogard** [comment]
Can you make a PR that's just the fix, and not all the whitespace changes? Otherwise you'll have merge conflicts.

**Comment by jogibear9988** [comment]
i used github editor... is only a one liner

**Comment by jogibear9988** [comment]
i'll fix

**Comment by jogibear9988** [comment]
Could you add a Editorconfig File to your Repo? Githubs Online Editor uses them (http://stackoverflow.com/a/33899831/579623).

**Comment by jbogard** [comment]
Fixes #1727

**Comment by jogibear9988** [comment]
Will you create a new Version on Nuget?

**Comment by jbogard** [comment]
Yeah. This is marked for the 5.2 release. Until then you can use the MyGet repo.

**Comment by jogibear9988** [comment]
When will the 5.2 be ready? Do you have a time schedule?

**Comment by jbogard** [comment]
Right now looking at releasing with .NET Standard 1.6/2.0. Is the MyGet release not working for you?

**Comment by jogibear9988** [comment]
i cannot use really! If I do, I've to setup MyGet on all my collegues computers...

**Comment by jbogard** [comment]
You can also just use a nuget.config file:

https://docs.nuget.org/ndocs/consume-packages/configuring-nuget-behavior

This is very common to do.

**Comment by jogibear9988** [comment]
Yes, I will look. But why will you wait wirh your bugfixed Version for a new NetStandart? Maybe there are new bugs to fix.

**Pull request merged**
