### PR TITLE
Fixed issue #1905 mapping nullable type to nullable type

### PR DESCRIPTION
**Pull request by jamesloi**
#1905 Resolving a nullable decimal to a nullable decimal throws Missing type map configuration or unsupported mapping at runtime. version 4.2.0. Aslo adding unit test.

### CODE REVIEW

**Comment by jbogard** [comment]
Build failed :(

**Comment by lbargaoanu** [comment]
This was handled in a different way in #1093.

**Comment by jamesloi** [comment]
@lbargaoanu was that merged back into the master? As the issue was still happening for me with the latest from master.

@jbogard fixed the build issue.

**Comment by lbargaoanu** [comment]
Try the MyGet build.

**Comment by jbogard** [comment]
@jamesloi it was merged into develop, not master. Master branch is the NuGet release branch, develop is MyGet.

**Comment by billrob** [comment]
FWIW, I don't think this is a good fix. The issue is the way ResolveUsing is handling nulls.  Not that is has to do with a nullable<T>.  I suspect if the non nullable<T> bug is fixed, the nullable<T> will get resolved as well.

**Comment by jbogard** [comment]
Yeah, this is fixed in the 5.0 release now.

**Pull request closed without merging**
