### PR TITLE
Revert "Merge pull request #2478 from AutoMapper/revert-2461-Destinat…

### PR DESCRIPTION
**Pull request by jbogard**
…ionPostfixWithMapFromString"

This reverts commit 66bcb3cac95188d010a6ad1ea697151221509c9f, reversing
changes made to 162739ccc829c471b5a23203156d02569596b907.

### CODE REVIEW

**Comment by jbogard** [comment]
@lbargaoanu well now this is failing 🤷‍♂️

**Comment by lbargaoanu** [comment]
I guess they interfere somehow.

**Comment by lbargaoanu** [comment]
Well, it passed last year :)

**Comment by jbogard** [comment]
lol well lgtm

**Pull request merged**
