### PR TITLE
Projecting Enum to Enum in another assembly throws an exception

### PR DESCRIPTION
**Pull request by nholling**

### CODE REVIEW

**Comment by yyjdelete** [comment]
Also failed ProjectTo with for Enum -> byte
byte is the underType of the enum, `public enum ModelStatus : byte`
`ProjectUsing` is an workaround, but is there other way to do this?

**Comment by lbargaoanu** [comment]
@yyjdelete Try the MyGet build.

**Comment by lbargaoanu** [comment]
I don't think this is worth fixing. One can work around it by creating a map for the enums and casting in ProjectUsing (or whatever works).

**Comment by yyjdelete** [comment]
@lbargaoanu 
Yes, you are right. But it's strange when using `v5.0.0-ci-1049`, the same Exception(maybe) is thrown without `ProjectUsing`, but an `NullReferenceException` is thrown when access ex.Message, seems another issue?
```
System.NullReferenceException: (locale message...)
   at AutoMapper.AutoMapperMappingException.get_Message()
```

**Comment by yyjdelete** [comment]
AutoMapperMappingException.Message is work well again in `v5.0.0-ci-1052`

**Comment by lbargaoanu** [comment]
@yyjdelete Yes, I saw that and fixed it yesterday.

**Pull request closed without merging**
