### PR TITLE
Create XpressionMapping

### PR DESCRIPTION
**Pull request by BlaiseD**
Hi. I have a proposal for the next version of AutoMapper.  When you have a second I'll appreciate your feedback.  It basically removes the need for projection in the data layer or the need to return an IQueryable from the data layer.

Thanks so much.

### CODE REVIEW

**Comment by jbogard** [comment]
Sure! What would you like me to look at? The PR doesn't seem to have any files in it?

**Comment by BlaiseD** [comment]
Thanks Jimmy,


I'm a github novice so probably missing something.  The fork is here: https://github.com/BlaiseD/AutoMapper with the proposed projects added.


I think AutoMapper is awesome - you can probably tell.


Best,

Blaise



[https://avatars2.githubusercontent.com/u/7595209?v=3&s=400]<https://github.com/BlaiseD/AutoMapper>

BlaiseD/AutoMapper · GitHub
AutoMapper - A convention-based object-object mapper in .NET.
Read more...<https://github.com/BlaiseD/AutoMapper>



________________________________

**Comment by jbogard** [comment]
Ah got it, I'll take a look!

**Comment by BlaiseD** [comment]
Did you ever get a chance to take a look Jimmy?  I did notice today #649 has made some similar progress.  Let me know.

Thanks.

**Comment by BlaiseD** [comment]
Replacing this pull request with #704.

**Pull request closed without merging**
