### PR TITLE
Drop netstandard13

### PR DESCRIPTION
**Pull request by jbogard**
And rev up to `net461` based on MS recommendation. Basically, `net461` has an issue with `netstandard2.0`, so we should target it explicitly.

This should simplify our dependencies, and fix folks that have to do weird binding redirects with `ValueTuple`.

### CODE REVIEW

**Comment by lbargaoanu** [comment]
We don't support 4.5 anymore.
4.7 projects  will use the 4.6.1 target and they will still have a reference to ValueTuple.
Platforms that don't support Reflection.Emit will have a reference to it.
Problematic  I'd say.

**Comment by jbogard** [comment]
Here's the recommendation: https://twitter.com/terrajobst/status/1040410118053982208

**Comment by lbargaoanu** [comment]
I guess 4.5 is old and the value tuple thing is a framework problem. So replacing 4.5 with 4.6.1 might not be a big deal. But I don't know how mobile platforms wil handle Reflection.Emit.

**Comment by jbogard** [comment]
@lbargaoanu They won't. They'll just get a `PlatformNotSupportedException`. Not much to do about it, basically the .NET team restored the reflection package back into `netstandard2.0` with the expectation that you just don't use those features in platforms that don't support it. I don't really want to create targets for all the mobile platforms since all we'd do is throw our own exception in those cases.

**Comment by lbargaoanu** [comment]
Reflection.Emit is part of [.Net Standard 2.1](https://blogs.msdn.microsoft.com/dotnet/2018/11/05/announcing-net-standard-2-1/).

**Pull request merged**
