### PR TITLE
Multiple IEnumerable interfaces

### LINKED ISSUE #1709: Automapper does not map Json.Net JObjects
Im trying to map an object that has a JObject field. Its fails when initialing. 

` Instance property 'Key' is not defined for type 'Newtonsoft.Json.Linq.JToken`

Could someone please help me?

### PR DESCRIPTION
**Pull request by lbargaoanu**
Fixes #1709.

### CODE REVIEW

**Comment by lbargaoanu** [comment]
This is done. I'm not sure why the last check-in wasn't built.

**Comment by jogibear9988** [comment]
Wen will this be merged?

**Comment by jogibear9988** [comment]
Could you Change the Assign in ExpressionExtension from 
    
            Assign(loopVar, Property(enumeratorVar, "Current")),

to

             Assign(loopVar, Convert(Property(enumeratorVar, "Current"), loopVar.Type)),

**Comment by jogibear9988** [comment]
And i could only compile .NET4 code with your changes. NetStandart has Errors inPprimitiveExtensions-26

      CS1061	'MemberInfo' does not contain a definition for 'MemberType' and no extension method 'MemberType' accepting a first argument of type 'MemberInfo' could be found (are you missing a using directive or an assembly reference?)

**Comment by jogibear9988** [comment]
You need to change the Line to:

         if(memberInfo == null || (!(memberInfo is FieldInfo) && !(memberInfo is PropertyInfo)))

**Comment by KasunKoswattha** [comment]
Will this fix the #1709

**Pull request merged**
