### PR TITLE
Applying partially trusted callers only for full .NET

### PR DESCRIPTION
**Pull request by jbogard**

### CODE REVIEW

**Comment by jbogard** [comment]
Closes #1685

**Comment by lbargaoanu** [comment]
So for example .NET Core loses performance for Windows Phone? :)

**Comment by jbogard** [comment]
Yes but it's offset because .NET Core is webscale

**Comment by jbogard** [comment]
I'm not sure the perf hits with the partial trust piece shows up in other areas. It's not a thing in .NET Core, doesn't seem to work in WinRT, and I don't think it's a thing in Xamarin either. From what I can see, the partial trust perf hit is only a thing in full .NET.

But it's hard to test tbqh

**Comment by lbargaoanu** [comment]
Yeah, maybe :)

**Comment by lbargaoanu** [comment]
Some ad-hoc testing suggests you're right. I see no overhead in .NET Core.

**Pull request merged**
