### PR TITLE
Lazily Mapped Queries

### PR DESCRIPTION
**Pull request by jbogard**
Rebased version of #997 
See also #871

### CODE REVIEW

**Comment by jbogard** [comment]
@gentledepp I've rebased your PR against latest develop. I think it's all good, can you take a look?

**Comment by gentledepp** [comment]
I apologize for my stupid question, but:

how can I "take a look at a pr"? 
Can I just clone automapper and then do something to get the very same build as you have it here? (I am sure that 's possible, but I am missing the buzzwords to google it up :-|)

**Comment by jbogard** [comment]
Well, at the least, check out the files changed in the tab in GitHub. You can download it if you like (the command line instructions can help there). But you'll probably know your changes enough to just use the GitHub UI.

I did do one last diff between your branch and my PR locally and it looked good too. It's just a lot to wade through like that.

**Comment by gentledepp** [comment]
Ok I see :)
I had a careful look at the files you're merging and everything looks ok, except the "todo.txt" where the only still unfinished todo is the "Projection/Select" stuff

**Comment by jbogard** [comment]
@gentledepp ping :)

**Comment by gentledepp** [comment]
@jbogard  pong? (I don't get that to be honest... :))

**Comment by TylerCarlson1** [comment]
@gentledepp ping to get your attention.  I guess to clarify todo.txt section of your last post

**Comment by gentledepp** [comment]
Ok. So what is still unclear?
I implemented nullpropagation, expansio  and parameterization. So the last thing missing would be handling projection.

**Comment by gentledepp** [comment]
We have been using those butts in production for several months now and it works like a charm :-D

**Comment by gentledepp** [comment]
Do you already know when you'll have time to merge this?
I would like to do a tiny bugfix, but I cannot "clone the PR", can I?

**Comment by TylerCarlson1** [comment]
@gentledepp  Yes you can and probably already have it.  It's branch gentledepp-lazilymappedqueries and you can make a PR to a PR.  @jbogard did it for your old PR before.

**Comment by gentledepp** [comment]
@TylerCarlson1
This would be awesome, however I googled for exactly that and did not find any tutorial or whatseover.
So I do not have any clue. 
In case you could send me a link, I would be really, really thankful :)

**Comment by TylerCarlson1** [comment]
I don't know of any tutorials per say.  It's exactly the same as making a PR for master.  Just instead of branching off of master branch Branch off gentledepp-lazilymappedqueries branch.  When you are done make a PR and when you get to the github PR page, change the branch from master to gentledepp-lazilymappedqueries.

I say just follow the normal GitHub process to make a PR and just make sure you are pulling and pull requesting from gentledepp-lazilymappedqueries instead of master.  Just have to pay close attention to which branch you are going to.

**Comment by jbogard** [comment]
Meh, it's not worth it. On the todo - what's an example of what's not working right now?

**Comment by jbogard** [comment]
And I'll merge this if everything looks OK from your side (besides the todo)

**Comment by gentledepp** [comment]
as for the "TODO" - I think I just did not do proper testing for the "projections" stuff.
You know - with OData, you can also specify some kind of "Select".

Also, what is not supported yet (in terms of OData only) is "expansion" - where you specify an expansion property (kust like ".Include(...)" in Entitiy Framework) and get those sub-elements as well.

**Comment by gentledepp** [comment]
Thanks for merging! :)

**Comment by gentledepp** [comment]
I just added some documentation for `UseAsDataSource` here:
https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions

You might want to take a look and give me some feedback? I think it is pretty clear though :)

**Comment by lbargaoanu** [comment]
@gentledepp There is already a separate page for UseAsDataSource.

**Comment by gentledepp** [comment]
Ok thanks. I will have a look at it.
but basically I believe that projectto and useasdatasource are very similar and should be explained together, so that we can explain the similarities and differences. Otherwise we would confuse our users. 
Did you read my changes?

**Comment by lbargaoanu** [comment]
No, I don't use it.

**Comment by TylerCarlson1** [comment]
@gentledepp As the person who wrote the original UseAsDataSource, I put it somewhere else because the page explaining ProjectTo was already long enough as is, and has been around for a long time, where UseAsDataSource is fairly new.

That being said I don't really have much of a preference for how it should be worded or organized anymore.

**Comment by gentledepp** [comment]
Yeah I understand that. It is kind of long. But putting it to a separate page would lead to duplicate sections, as they are too similar. :-\
Maybe @jbogard has an idea?

**Comment by gentledepp** [comment]
@jbogard: I would like help this featuer to get some more attention.
So I could offer to write a blog post, explaining how UseAsDataSource() along with all its new features can be used to create an Asp.NET Web API backed with EntityFramework. 
The only thing is: I do not yet have a blog really and even if, I surely do not have quite an audience as you have.
So maybe you can prepare everything and you just poste it on yours under your name? (feel free to censor anything you like)

**Comment by lbargaoanu** [comment]
@gentledepp I've read your changes and I've reverted some of them and I've moved the rest to the dedicated page.
I think it's fair to say that most people need ProjectTo and have no need for UseAsDataSource.
For someone that tries to understand what ProjectTo is all about it's not helpful to have to go through all that extra stuff. Maybe add a link?
And the comparison, that's misleading at best. ProjectTo will pass filters to the database and will do that even when it's not the last in the call chain.
I think it's best if you open an isssue about the docs change, make a gist with your proposed changes and wait for feedback.
I realize this might take a while, but hopefully the result would be better docs.

**Comment by gentledepp** [comment]
> ProjectTo will pass filters to the database and will do that even when it's not the last in the call chain.
Are you sure? Because that not being the case was the reason for me to put so much effort in UseAsDataSource in the first place 0_0
As to your changes and the docs issue: I think you are right.
The reason I wanted to put the UseAsDataSource docs to the Queryable Extensions page was, that 
1) I originally was confused, as I assumed ProjectTo to forward chagnes to the database even if it was not the last in the call chain, and it just didn't.
2) Then I opened an issue asking if someone could implement just that
3) and in thrn @TylerCarlson1  answered that he had already done so with UseAsDataSource.
I was not aware of that and did not find it in the docs myself.

Therefore: I am not offended at all - I just thought that I had to put documentation somewhere people could find it, and did so. 

What I think would be important for the docs is to point out that
1) automapper can map two different object types (e.g. Dto<=>Entity)
2) automapper can as well map expressions of two different types (e.g. IQueryable<Dto><=>IQuerayble<Entity>
       and in case 2) point out the differences between UseAsDataSource() and ProjectTo<> 
       (and again: lazy evaluation is not supported by ProjectTo<> and the only reason why UseAsDataSource() exists -> please double check that. :))

**Comment by lbargaoanu** [comment]
I did double check. I'm sure it needs more documentation, we just have to make sure it is correct.

**Pull request merged**
