### PR TITLE
ForAllOtherMembers #602

### PR DESCRIPTION
**Pull request by lbargaoanu**

### CODE REVIEW

**Comment by jbogard** [comment]
Merge conflicts :(

**Comment by lbargaoanu** [comment]
Updated.

**Comment by lbargaoanu** [comment]
So you don't want the feature, right? :)

**Comment by jbogard** [comment]
I have no idea why i closed this. Reopen?

**Comment by lbargaoanu** [comment]
I've restored the branch, but only you can reopen the PR I believe.

**Pull request merged**
