### PR TITLE
.NET Foundation prep

### PR DESCRIPTION
**Pull request by jbogard**
@lbargaoanu @TylerCarlson1 one repo change here, I moved the sln file up to the root.

@jongalloway this is the "repo structure" guidance. Let me know if anything is missing.

### CODE REVIEW

**Comment by jbogard** [comment]
The other big changes are the readme, contribution guidelines, and issue template

**Comment by jbogard** [comment]
@TylerCarlson1 @lbargaoanu any objections to merge?

**Comment by lbargaoanu** [comment]
Probably not :)

**Comment by TylerCarlson1** [comment]
Definitely not

**Pull request merged**
