### PR TITLE
bugfix empty name for example generated by Castle Dnyamic Proxy

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by jogibear9988** [comment]
I've only changed line 92, but I created the edit via github, maybe cause of that the other lines are changed

**Comment by jogibear9988** [comment]
will this get merged?

**Comment by lbargaoanu** [comment]
There is no need to explicitly check for null. Using the static Equals would do.

**Comment by jbogard** [comment]
There's no test here, is it possible to write a test to show how this behavior should work? Also, I'm not entirely sure this addresses your issue, since you're calling CreateMap with runtime values.

**Comment by jogibear9988** [comment]
i've tested it, with my null check it works

**Comment by jogibear9988** [comment]
look at issue #1596, you could use my castle example for a test

**Pull request closed without merging**
