### PR TITLE
Collection is read-only exception when try to map to ICollection with fixed size

### PR DESCRIPTION
**Pull request by Tasteful**
Unit tests and fix in the expression builder to do additional check if the destination collection is an read only array.

#1973

### CODE REVIEW

**Comment by lbargaoanu** [comment]
In my view, this is a hack. Allow passing an invalid destination for this mapper and then ignoring it. Something explicit like DoNotUseDestinationValue makes more sense to me.

**Comment by Tasteful** [comment]
The defined type is `ICollection<AA>` but is created of an instance of `AA[]`. The Array `AA[]` implements `ICollection<AA>` interface. So both the declaration with `ICollection<AA>` and assigning with `AA[]` is valid of the coding perspective.

`CollectionMapper` is using the `Add` method on the array and regarding to documentation should throw exception, see https://msdn.microsoft.com/en-us/library/bb342410%28v=vs.110%29?f=255&MSPPError=-2147217396 and this known situation is not handled in the `ICollectionMapper`.

**Comment by lbargaoanu** [comment]
Yes, because the array mapper handles this case. Maybe @jbogard will see it your way.

**Comment by Tasteful** [comment]
How can I setup in the configuration that the `ArrayMapper` should be used instead of the `ICollectionMapper` if the destination definition type is `ICollection` but have a run time value type of `Array`?

**Comment by Tasteful** [comment]
Hack to do this check outside without modification in `CollectionMapper` but I think that will take extra performance for the operation.
```
                var propertiesTypeCache = new ConcurrentDictionary<Type, Lazy<ICollection<PropertyInfo>>>();
                var typeActivator = new ConcurrentDictionary<Type, Lazy<Func<IList>>>();
                cfg.ForAllMaps((typeMap, mapping) => mapping.BeforeMap((src, dest) =>
                {
                    if (dest != null)
                    {
                        foreach (var prop in propertiesTypeCache.GetOrAdd(dest.GetType(), t => new Lazy<ICollection<PropertyInfo>>(()=> t.GetProperties().Where(x => x.PropertyType.IsGenericType && x.PropertyType.GetGenericTypeDefinition() == typeof(ICollection<>)).ToList())).Value)
                        {
                            var items = prop.GetValue(dest) as Array;
                            if (items != null)
                            {
                                var collection = typeActivator.GetOrAdd(prop.PropertyType, t => new Lazy<Func<IList>>(() =>
                                {
                                    var a = typeof(List<>).MakeGenericType(t.GetGenericArguments());
                                    return () => (IList)Activator.CreateInstance(a);
                                })).Value();

                                foreach (var item in items)
                                {
                                    collection.Add(item);
                                }

                                prop.SetValue(dest, collection);
                            }
                        }
                    }
                }));
```

**Comment by lbargaoanu** [comment]
DoNotInline would force using the runtime types, but that crashes in the array mapper. That could be easily fixed. But does it make sense? :)

**Pull request closed without merging**
