### PR TITLE
Collection pure expressions

### PR DESCRIPTION
**Pull request by TylerCarlson1**
Finishes off #1329 to make all the collection mappings pure generated expressions, with only calling what is needed to do the map.  Well maybe there's still a few things left, like double checking for nulls when map after checking null before.

Have examples of deeptype map config
```
(src, dest, ctxt) =>
{
    if (src == null)
    {
        null;
    }
    else
    {
        ctxt.TypeMap = AutoMapper.TypeMap;
        var propertyContext = new ResolutionContext(ctxt);
        var dest = dest ?? new CustomerDTO();
        ctxt.BeforeMap(dest);
        try
        {
            dest.AddressCity = ((src == null) ? null : src.Address == null) ? null : src.Address.City;
        }
        catch (AutoMapperMappingException ex)
        {
            ex.PropertyMap = AutoMapper.PropertyMap;
            throw;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException(ctxt, ex, AutoMapper.PropertyMap);
        }

        try
        {
            dest.WorkAddresses = if ((src == null) ? null : src.WorkAddresses == null)
            {
                new List<AddressDTO>();
            }
            else
            {
                var d = new List<AddressDTO>();
                var itemContext = new ResolutionContext(ctxt);
                var enumerator = src == null) ? null : src.WorkAddresses.GetEnumerator(;
                while (true)
                {
                    if (enumerator.MoveNext())
                    {
                        var item = enumerator.Current;
                        d.Add(itemContext.Map(item, null));
                    }
                    else
                    {
                        break;
                    }
                }

                return d;
            };
        }
        catch (AutoMapperMappingException ex)
        {
            ex.PropertyMap = AutoMapper.PropertyMap;
            throw;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException(ctxt, ex, AutoMapper.PropertyMap);
        }

        try
        {
            dest.Addresses = ((src == null) ? null : src.Addresses == null)
                ? new AddressDTO[0]
                : ArrayMapper.Map((src == null) ? null : src.Addresses, ctxt, (item, itemContext) => itemContext.Map(item, null));
        }
        catch (AutoMapperMappingException ex)
        {
            ex.PropertyMap = AutoMapper.PropertyMap;
            throw;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException(ctxt, ex, AutoMapper.PropertyMap);
        }

        try
        {
            dest.HomeAddress = propertyContext.Map((src == null) ? null : src.HomeAddress, null);
        }
        catch (AutoMapperMappingException ex)
        {
            ex.PropertyMap = AutoMapper.PropertyMap;
            throw;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException(ctxt, ex, AutoMapper.PropertyMap);
        }

        try
        {
            dest.Address = (src == null) ? null : src.Address;
        }
        catch (AutoMapperMappingException ex)
        {
            ex.PropertyMap = AutoMapper.PropertyMap;
            throw;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException(ctxt, ex, AutoMapper.PropertyMap);
        }

        try
        {
            dest.Name = (src == null) ? null : src.Name;
        }
        catch (AutoMapperMappingException ex)
        {
            ex.PropertyMap = AutoMapper.PropertyMap;
            throw;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException(ctxt, ex, AutoMapper.PropertyMap);
        }

        try
        {
            dest.Id = (src == null) ? default(int) : src.Id;
        }
        catch (AutoMapperMappingException ex)
        {
            ex.PropertyMap = AutoMapper.PropertyMap;
            throw;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException(ctxt, ex, AutoMapper.PropertyMap);
        }

        ctxt.AfterMap(dest);
        return dest;
    }
}
```

```
(src, dest, ctxt) =>
{
    if (src == null)
    {
        null;
    }
    else
    {
        ctxt.TypeMap = AutoMapper.TypeMap;
        var dest = dest ?? new Address();
        ctxt.BeforeMap(dest);
        try
        {
            dest.Country = (src == null) ? null : src.Country;
        }
        catch (AutoMapperMappingException ex)
        {
            ex.PropertyMap = AutoMapper.PropertyMap;
            throw;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException(ctxt, ex, AutoMapper.PropertyMap);
        }

        try
        {
            dest.City = (src == null) ? null : src.City;
        }
        catch (AutoMapperMappingException ex)
        {
            ex.PropertyMap = AutoMapper.PropertyMap;
            throw;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException(ctxt, ex, AutoMapper.PropertyMap);
        }

        try
        {
            dest.Street = (src == null) ? null : src.Street;
        }
        catch (AutoMapperMappingException ex)
        {
            ex.PropertyMap = AutoMapper.PropertyMap;
            throw;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException(ctxt, ex, AutoMapper.PropertyMap);
        }

        try
        {
            dest.Id = (src == null) ? default(int) : src.Id;
        }
        catch (AutoMapperMappingException ex)
        {
            ex.PropertyMap = AutoMapper.PropertyMap;
            throw;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException(ctxt, ex, AutoMapper.PropertyMap);
        }

        ctxt.AfterMap(dest);
        return dest;
    }
}
```

```
(src, dest, ctxt) =>
{
    if (src == null)
    {
        null;
    }
    else
    {
        ctxt.TypeMap = AutoMapper.TypeMap;
        var dest = dest ?? new AddressDTO();
        ctxt.BeforeMap(dest);
        try
        {
            dest.Country = (src == null) ? null : src.Country;
        }
        catch (AutoMapperMappingException ex)
        {
            ex.PropertyMap = AutoMapper.PropertyMap;
            throw;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException(ctxt, ex, AutoMapper.PropertyMap);
        }

        try
        {
            dest.City = (src == null) ? null : src.City;
        }
        catch (AutoMapperMappingException ex)
        {
            ex.PropertyMap = AutoMapper.PropertyMap;
            throw;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException(ctxt, ex, AutoMapper.PropertyMap);
        }

        try
        {
            dest.Id = (src == null) ? default(int) : src.Id;
        }
        catch (AutoMapperMappingException ex)
        {
            ex.PropertyMap = AutoMapper.PropertyMap;
            throw;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException(ctxt, ex, AutoMapper.PropertyMap);
        }

        ctxt.AfterMap(dest);
        return dest;
    }
}
```

### CODE REVIEW

**Comment by TylerCarlson1** [comment]
Example from `When_mapping_to_a_generic_dictionary_with_mapped_value_pairs` to show off enumerable to dictionary example
```
(src, dest, ctxt) =>
{
    if (src == null)
    {
        null;
    }
    else
    {
        ctxt.TypeMap = AutoMapper.TypeMap;
        var dest = dest ?? new Destination();
        ctxt.BeforeMap(dest);
        try
        {
            dest.Values = if ((src == null) ? null : src.Values == null)
            {
                new Dictionary<string, DestinationValue>();
            }
            else
            {
                var d = new Dictionary<string, DestinationValue>();
                var itemContext = new ResolutionContext(ctxt);
                // This null check is redundant should be removed
                var enumerator = src == null) ? null : src.Values.GetEnumerator(;
                while (true)
                {
                    if (enumerator.MoveNext())
                    {
                        var item = enumerator.Current;
                        d.Add(new KeyValuePair<string, DestinationValue>(item.Key, itemContext.Map(item.Value, null)));
                    }
                    else
                    {
                        break;
                    }
                }

                return d;
            };
        }
        catch (AutoMapperMappingException ex)
        {
            ex.PropertyMap = AutoMapper.PropertyMap;
            throw;
        }
        catch (Exception ex)
        {
            throw new AutoMapperMappingException(ctxt, ex, AutoMapper.PropertyMap);
        }

        ctxt.AfterMap(dest);
        return dest;
    }
}
```

**Comment by TylerCarlson1** [comment]
Oh yeah and this will conflict with #1341 because I comment out MapCollection code where in that one it's deleted completely

**Comment by jbogard** [comment]
OK so you wanna fix the merge conflict? I just merged my object mapper one.

**Comment by TylerCarlson1** [comment]
Merged.  You and @lbargaoanu can purtty it up all you want I guess. I think I'm done with changing big things for now.  Well until you bait me with another PR that I think the implementation is horrible again.  Lol

**Comment by jbogard** [comment]
lol well...my next big idea is to only build nested resolution contexts unless I determine through configuration that you've actually used it. Then the exception blocks already have the scope you need, so I could just set those properties on the exception object.

**Comment by TylerCarlson1** [comment]
Yea that doesn't sound like a whole lot of benefit, over all and I can't imagine an example.  Actually I don't think you can do that anywhere right now.  So that means I'll just do a 180 once I actually see some code to implement it.

**Comment by jbogard** [comment]
Speculation at this point really, I'll need to run the profiler to see where the time is spent.

**Pull request merged**
