### PR TITLE
Only a global AllowNullCollections

### LINKED ISSUE #1618: Profile.AllowNullCollections ignored?
The `Profile.AllowNullCollections` property seems to be being missed in 5.0.2 and beyond. Moving the code out of the `Configure` method into a constructor results in the same behavior.

```
class Program
{
    static void Main(string[] args)
    {
        var mapper = new MapperConfiguration(cfg =>
        {
            cfg.AddProfile(new TestMappingProfile());
        }).CreateMapper();

        var isNull = mapper.Map<Source, Destination>(new Source()).Ints == null;
        // "true" in 4.2.1
        // "false" in 5.0.2+
    }
}

class TestMappingProfile : Profile
{
    protected override void Configure()
    {
        AllowNullCollections = true;
        CreateMap<Source, Destination>();
    }
}

class Source
{
    public IEnumerable<int> Ints { get; set; }
}

class Destination
{
    public IEnumerable<int> Ints { get; set; }
}
```

### PR DESCRIPTION
**Pull request by lbargaoanu**
Closes #1618.
And if this makes sense, AllowNullDestinationValues too. Or just wait for someone to complain.

### CODE REVIEW

**Comment by jbogard** [comment]
Regarding the comment on #1618 I wonder if it would be better to do the thing where we apply the global configuration only if the profile configuration isn't set?

**Comment by lbargaoanu** [comment]
I don't know. Having these things per profile too seems complicated and error prone to me. We had similar issues before.

**Comment by jbogard** [comment]
What's the point of profiles then? Just naming conventions?

**Comment by TylerCarlson1** [comment]
I like the flexibility of it, even if you could possibly miss it.  And who knows if someone next version will go HEY where did my Profile settings go?  I needed that for ____.

**Comment by lbargaoanu** [comment]
Profiles are used to split the configuration per module. Then you gather it all in one place. If you look at it this way, I think global settings make sense. You can have multiple configurations if you want.

**Comment by lbargaoanu** [comment]
But if some things work per profile, naming conventions for example, then I guess all should work per profile :) (and in the same way) Because it used to be the only way to separate configuration. Right now separate configurations seem to me a better way to do that, but I guess that would break things.

**Pull request closed without merging**
