### PR TITLE
Consolidating ProjectUsing to ConvertUsing

### PR DESCRIPTION
**Pull request by jbogard**
Per discussion in #2795

### CODE REVIEW

**Comment by lbargaoanu** [comment]
This needs a page in the docs explaining what changed, how to upgrade and the breaking scenarios.

**Comment by jbogard** [comment]
@lbargaoanu added an 8.0 migration guide

**Comment by lbargaoanu** [comment]
Smth about ConstructUsing and ConstructProjectionUsing. Maybe also a note that until now ConvertUsing and ConstructUsing were used only for Map.

**Comment by jbogard** [comment]
The other changes will be in subsequent PRs.

**Pull request merged**
