### PR TITLE
Mapper.Initialize now can be called multiple times

### PR DESCRIPTION
**Pull request by jbogard**
With additive type maps.

### CODE REVIEW

**Comment by jbogard** [comment]
The configuration was never read-only. Between open generics, convention type maps, and dynamically created maps, we've needed to have our type map list dynamic. So the capability was always there at least.

This also doesn't make Initialize calls commutative. Once the initial...initialization happens, subsequent calls only create new type maps.

Overall, I think we need to enable `services.AddAutoMapper` to be called multiple times, even with static registration. Maybe that's putting a lock/Lazy inside of that code?

**Comment by lbargaoanu** [comment]
Yes, but that's different. All that code does is CreateTypeMap and it takes one global lock in the end, that's why we don't see concurrency issues anymore. A static AddAutoMapper could replace the static instance.

**Comment by jbogard** [comment]
I’ll do that then. Make AddAutoMapper idempotent, for the static route at
least.

**Comment by jbogard** [comment]
Most of the problems seem to be in ASP.NET Core, so I just removed static registration altogether:

https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/pull/58

**Pull request closed without merging**
