### PR TITLE
Always map array contents & remove the primitive array mapper.

### PR DESCRIPTION
**Pull request by lbargaoanu**
I don't think PrimitiveArrayMapper is worth keeping as an optimization (presumably that was the intent).

### CODE REVIEW

**Comment by jbogard** [comment]
Yeah, that was the intent. There was an issue a long time ago where someone was mapping a really large byte array, and Array.Copy was blazing fast.

**Comment by jbogard** [comment]
I found it! #279 but I don't know, given the numbers, how much was just old AutoMapper slowness

**Comment by lbargaoanu** [comment]
I've done some ad-hoc microbenchmarks and yes, it's faster, but I think for large arrays you should just avoid copying them in the first place. And for smaller ones, it's just pennies.

**Comment by lbargaoanu** [comment]
I think my point here is clear. The ArrayMapper does the right thing fast enough, the PrimitiveArrayMapper is faster because it doesn't really map, it just copies. But if you want to keep it, I should revert that part and leave the fix in.

**Comment by jbogard** [comment]
So in the large array case, what SHOULD be the behavior? Suppose someone has something like an image stored as a byte array, or a document. When I tested with a large byte array (1M items), there was a huge time difference between the two.

**Comment by lbargaoanu** [comment]
All I see is that the ArrayMapper is twice as slow. But it maps :) So if you have a map, it will call it, as with any other type. This should be the default behavior in my view. Users should special case them in they need reference assignment (most likely, I believe) or Array.Copy.

**Comment by jbogard** [comment]
Sounds good.

**Comment by lbargaoanu** [comment]
For future reference. The way to special case them would be AfterMap or a type converter (ResolveUsing or MapFrom wouldn't work). Right? :)

**Pull request merged**
