### PR TITLE
Expression optimization

### PR DESCRIPTION
**Pull request by jbogard**
IT'S A RACE

### CODE REVIEW

**Comment by jbogard** [comment]
@TylerCarlson1 

At this point I'm trying to optimize the lambda created:

```
.Lambda #Lambda1<System.Func`3[System.Object,AutoMapper.ResolutionContext,System.Object]>(
    System.Object $src,
    AutoMapper.ResolutionContext $ctxt) {
    .If ($src == null) {
        null
    } .Else {
        .Block(
            AutoMapperSamples.Flattening.OrderDto $mapObj,
            AutoMapperSamples.Flattening.Order $mapFrom) {
            $mapFrom = (AutoMapperSamples.Flattening.Order)$src;
            $mapObj = (AutoMapperSamples.Flattening.OrderDto).Block(System.Object $destination) {
                $destination = .If ((AutoMapperSamples.Flattening.OrderDto)$ctxt.DestinationValue != .Default(AutoMapperSamples.Flattening.OrderDto)) {
                    (AutoMapperSamples.Flattening.OrderDto)$ctxt.DestinationValue
                } .Else {
                    .New AutoMapperSamples.Flattening.OrderDto()
                };
                .If ($destination == null) {
                    .Throw .Constant<System.InvalidOperationException>(System.InvalidOperationException: Cannot create destination object. )
                } .Else {
                    .Default(System.Void)
                };
                $destination
            };
            .Call $ctxt.BeforeMap((System.Object)$mapObj);
            .Try {
                .Block<System.Void>() {
                    $mapObj.Total = .Call $mapFrom.GetTotal()
                }
            } .Catch (AutoMapper.AutoMapperMappingException $ex) {
                .Block() {
                    $ex.PropertyMap = .Constant<AutoMapper.PropertyMap>(AutoMapper.PropertyMap);
                    .Rethrow
                }
            } .Catch (System.Exception $ex) {
                .Throw .New AutoMapper.AutoMapperMappingException(
                    $ctxt,
                    $ex,
                    .Constant<AutoMapper.PropertyMap>(AutoMapper.PropertyMap))
            };
            .Try {
                .Block<System.Void>() {
                    $mapObj.CustomerName = .If (.If ($mapFrom == .Default(AutoMapperSamples.Flattening.Order)) {
                        .Default(AutoMapperSamples.Flattening.Customer)
                    } .Else {
                        $mapFrom.Customer
                    } == .Default(AutoMapperSamples.Flattening.Customer)) {
                        .Default(System.String)
                    } .Else {
                        ($mapFrom.Customer).Name
                    }
                }
            } .Catch (AutoMapper.AutoMapperMappingException $ex) {
                .Block() {
                    $ex.PropertyMap = .Constant<AutoMapper.PropertyMap>(AutoMapper.PropertyMap);
                    .Rethrow
                }
            } .Catch (System.Exception $ex) {
                .Throw .New AutoMapper.AutoMapperMappingException(
                    $ctxt,
                    $ex,
                    .Constant<AutoMapper.PropertyMap>(AutoMapper.PropertyMap))
            };
            .Call $ctxt.AfterMap((System.Object)$mapObj);
            (System.Object)$mapObj
        }
    }
}
```

I don't think that destination == null check is needed, if you can't create the destination type, you'll know at config time.

**Comment by TylerCarlson1** [comment]
You are much further along than I am at this point.  Haven't gotten around to constructor parameters, just wanted the expression to pass over instead of invoking the CreateCtor function call, Which it looks like you did.

For your destination == null check, I think you are right.  The constructor will more than likely throw an exception I believe.  Not 100% sure but it looks like it's not needed.

**Comment by TylerCarlson1** [comment]
Yea you can just get rid of the whole block wrapper and destination variable if you want.  I added it at the very end just cause the original had it.  Most of the testing was done without that Block statement.

Just remove the block and `Assign(mapObj, getDest)`

**Comment by jbogard** [comment]
@TylerCarlson1 done! Thanks again for getting this working. I compared it to 3.x and 4.x and it's kinda crazy how much faster it is at this point.

Now I'm kinda curious to how this works vs. ExpressMapper. Should be easy to compare expression trees.

**Comment by TylerCarlson1** [comment]
Anything but simple mapping it should be about same.  Collections, and sub Map calls AutoMapper might do worse on cause it has to check types again.  Oh and exception handling with try catches for better error messages.

**Comment by TylerCarlson1** [comment]
Are you going to merge it, or do you want to wait for that block statement to move out?

Also with IObjectMapper refactoring are you working on that?  Don't want to start a race I'm already loosing again :)

**Comment by jbogard** [comment]
Lol no I was having an internal debate.

Those try-catches around every property set annoy me. And the
BeforeMap/AfterMap that I put in for IMappingOperationOptions that I now
regret. The current expression is just really complicated for me.

**Comment by jbogard** [comment]
Here's AutoMapper now:

```
.Lambda #Lambda1<System.Func`3[System.Object,AutoMapper.ResolutionContext,System.Object]>(
    System.Object $src,
    AutoMapper.ResolutionContext $ctxt) {
    .If ($src == null) {
        null
    } .Else {
        .Block(
            AutoMapper.UnitTests.BasicFlattening+AddressDTO $mapObj,
            AutoMapper.UnitTests.BasicFlattening+Address $mapFrom) {
            $mapFrom = (AutoMapper.UnitTests.BasicFlattening+Address)$src;
            $mapObj = (AutoMapper.UnitTests.BasicFlattening+AddressDTO).Block(System.Object $destination) {
                $destination = .If ((AutoMapper.UnitTests.BasicFlattening+AddressDTO)$ctxt.DestinationValue != .Default(AutoMapper.UnitTests.BasicFlattening+AddressDTO)) {
                    (AutoMapper.UnitTests.BasicFlattening+AddressDTO)$ctxt.DestinationValue
                } .Else {
                    .New AutoMapper.UnitTests.BasicFlattening+AddressDTO()
                }
            };
            .Call $ctxt.BeforeMap((System.Object)$mapObj);
            .Try {
                .Block<System.Void>() {
                    $mapObj.Country = .If ($mapFrom == .Default(AutoMapper.UnitTests.BasicFlattening+Address)) {
                        .Default(System.String)
                    } .Else {
                        $mapFrom.Country
                    }
                }
            } .Catch (AutoMapper.AutoMapperMappingException $ex) {
                .Block() {
                    $ex.PropertyMap = .Constant<AutoMapper.PropertyMap>(AutoMapper.PropertyMap);
                    .Rethrow
                }
            } .Catch (System.Exception $ex) {
                .Throw .New AutoMapper.AutoMapperMappingException(
                    $ctxt,
                    $ex,
                    .Constant<AutoMapper.PropertyMap>(AutoMapper.PropertyMap))
            };
            .Try {
                .Block<System.Void>() {
                    $mapObj.City = .If ($mapFrom == .Default(AutoMapper.UnitTests.BasicFlattening+Address)) {
                        .Default(System.String)
                    } .Else {
                        $mapFrom.City
                    }
                }
            } .Catch (AutoMapper.AutoMapperMappingException $ex) {
                .Block() {
                    $ex.PropertyMap = .Constant<AutoMapper.PropertyMap>(AutoMapper.PropertyMap);
                    .Rethrow
                }
            } .Catch (System.Exception $ex) {
                .Throw .New AutoMapper.AutoMapperMappingException(
                    $ctxt,
                    $ex,
                    .Constant<AutoMapper.PropertyMap>(AutoMapper.PropertyMap))
            };
            .Try {
                .Block<System.Void>() {
                    $mapObj.Id = .If ($mapFrom == .Default(AutoMapper.UnitTests.BasicFlattening+Address)) {
                        .Default(System.Int32)
                    } .Else {
                        $mapFrom.Id
                    }
                }
            } .Catch (AutoMapper.AutoMapperMappingException $ex) {
                .Block() {
                    $ex.PropertyMap = .Constant<AutoMapper.PropertyMap>(AutoMapper.PropertyMap);
                    .Rethrow
                }
            } .Catch (System.Exception $ex) {
                .Throw .New AutoMapper.AutoMapperMappingException(
                    $ctxt,
                    $ex,
                    .Constant<AutoMapper.PropertyMap>(AutoMapper.PropertyMap))
            };
            .Call $ctxt.AfterMap((System.Object)$mapObj);
            (System.Object)$mapObj
        }
    }
}
```

And here's Mapster:

```
.Lambda #Lambda1<System.Func`2[Benchmark.Classes.Customer,Benchmark.Classes.CustomerDTO]>(Benchmark.Classes.Customer $var1)
{
    .If ($var1 == null) {
        null
    } .Else {
        .New Benchmark.Classes.CustomerDTO(){
            Id = $var1.Id,
            Name = $var1.Name,
            Address = .If ($var1.Address == null) {
                null
            } .Else {
                .New Benchmark.Classes.Address(){
                    Id = ($var1.Address).Id,
                    Street = ($var1.Address).Street,
                    City = ($var1.Address).City,
                    Country = ($var1.Address).Country
                }
            },
            HomeAddress = .If ($var1.HomeAddress == null) {
                null
            } .Else {
                .New Benchmark.Classes.AddressDTO(){
                    Id = ($var1.HomeAddress).Id,
                    City = ($var1.HomeAddress).City,
                    Country = ($var1.HomeAddress).Country
                }
            },
            Addresses = .Call (Mapster.TypeAdapter`2[Benchmark.Classes.Address[],Benchmark.Classes.AddressDTO[]].Map).Invoke($var1.Addresses)
            ,
            WorkAddresses = .Call (Mapster.TypeAdapter`2[System.Collections.Generic.ICollection`1[Benchmark.Classes.Address],System.Collections.Generic.List`1[Benchmark.Classes.AddressDTO]].Map).Invoke($var1.WorkAddresses)
            ,
            AddressCity = .If ($var1.Address == null) {
                null
            } .Else {
                ($var1.Address).City
            }
        }
    }
}
```
The biggest thing I've always cared about was catching nulls, which both do. But there's just a lot going on in AutoMapper's still.

**Comment by TylerCarlson1** [comment]
I don't think the try catches give much of a performance hit.  I could be wrong though.
Maybe those can be deferred to IObjectMapper expressions or something, but without them you can't tell which property map failed in your exception chain.  Well you can't as far as I can tell, without some super clever way to move positions.  Other option is to invoke a function that makes the lambda smaller, like AutoTryCatch or something

There's obviously duplicate if default checks and things like that.  src was already checked for null, so there's no reason to recheck it.  Unless you think the cast will cause mapFrom to be null.

The before and after maps can work on the same principle as the before and after maps for typemap.  If they exist put them in there, if not then don't.  Also I would prefer to have the before and after maps be expressions and put them into the code instead of invoking.

**Comment by TylerCarlson1** [comment]
Also there's 2 things with mapster.

1.  I don't know how you do that new with setting properties in the brackets.  Couldn't figure that out
2.  This expression seems to create a new item does it not try to set properties on an item that already exists?

**Comment by jbogard** [comment]
Well I did some more benchmarking to compare in a more raw form what our stuff does vs. bare metal. Putting into C# code the *exact* set of operations, and it looks like capturing all that information we do adds about 25% overhead to just the mapping of one object to another. All the other stuff on top adds more.

So this one essentially is good to go.

**Comment by TylerCarlson1** [comment]
Now just need to get the stuff outside the expression now I guess.  That would help with sub Map calls as well.  Or the expression conversion mapping. Or it's good enough for now and just wait for someone else to blog about mapster performance gain again.

**Comment by jbogard** [comment]
Ha! So one.....laaaasst thing I'm looking at is removing some of the ambiguity around resolving a mapping function based on a type. We have `source?.GetType() ?? sourceType` in too many places. That would help us get to a place where I have a single type pair that resolves a `Func<TSource, TDestination, ResolutionContext, TDestination>`. That's my ideal.

**Pull request merged**
