### PR TITLE
Allow disabling the default naming convention

### PR DESCRIPTION
**Pull request by lbargaoanu**
#900

### CODE REVIEW

**Comment by jbogard** [comment]
Soooooo I don't think this is the right fix. Probably fixing the existing regex, but in #900 it should probably just use a more appropriate naming convention. A regex can't detect every possibility I think.

**Comment by lbargaoanu** [comment]
I think you should be able to disable the naming convention no matter what :)

**Comment by jbogard** [comment]
What would that do, though? You could always replace it, but there has to
be something.

**Comment by lbargaoanu** [comment]
Well, nothing :) If the splitting expression doesn't really split anything, it's like having no naming convention whatsoever.

**Comment by lbargaoanu** [comment]
Close or rebase? :)

**Comment by lbargaoanu** [comment]
@jbogard I've pointed people to this PR more than a few times. Perhaps reconsider? :)

**Comment by jbogard** [comment]
Maybe this is an "ExactMatchNamingConvention"?

**Comment by lbargaoanu** [comment]
I don't know. But usually people are surprised that the default configuration can lead to these situations, hence the original intent.

**Comment by jbogard** [comment]
I would be OK with having a naming convention that's exact match that you have to set, versus removing it and defaulting it to an exact match.

**Comment by lbargaoanu** [comment]
OK, I guess that would work too. It's a convenience thing after all.

**Pull request closed without merging**
