### PR TITLE
Sdk style tests

### LINKED ISSUE #2179: Make the test projects SDK style and xplat
And also execute tests on all supported platforms.

This will mean we need to get off of Fixie and onto xUnit.

### PR DESCRIPTION
**Pull request by jbogard**
Fixes #2179

### CODE REVIEW

**Comment by lbargaoanu** [comment]
As far as I can tell, in VS tests run only on .NET 4.5, but much slower.

**Comment by jbogard** [comment]
Yeah, that's just for people that don't have any other test runner. As punishment I guess, it also only supports .NET 4.5, not .NET Core

**Comment by lbargaoanu** [comment]
All right :) So what do you use, ReSharper?

**Comment by jbogard** [comment]
TestDriven.net but R# when I want to do test sessions. That package is just
to enable xUnit at least from their docs

**Comment by lbargaoanu** [comment]
I'm unable to get any significant speed up by running the tests in parallel, but maybe, for testing purposes, it would still be a better idea to run them in parallel.

**Comment by jbogard** [comment]
Ah yes I guess we don't use the static API in the tests

**Pull request merged**
