### PR TITLE
We have to set everything in the plan, we don't get a second chance

### PR DESCRIPTION
**Pull request by lbargaoanu**
It's like...be aggressive :)

### CODE REVIEW

**Comment by jbogard** [comment]
Does this fix another issue?

**Comment by lbargaoanu** [comment]
https://stackoverflow.com/questions/45215011/self-referencing-loop-causing-stack-overflow-with-map/

**Comment by lbargaoanu** [comment]
This is too aggressive I think :) The original idea was not bad, if you start from a map and you need it again while building the plan, you have recursion. But Seal is called only once, that's why it didn't work. Now just because you use a map twice in different levels, it would call it recursion. But it isn't. If I want to do this in one pass I think I need to also store the maps that lead to where I am in the plan.

**Comment by lbargaoanu** [comment]
I think this is done.

**Pull request merged**
