### PR TITLE
Multiple sources of the same type to one destination - aka $.extend

### PR DESCRIPTION
**Pull request by andrewm1986**
Referencing issue #1015 

Basic unit tests and enough scaffold code to compile - does not work and fails tests.

This should give you an idea of what I am imagining before I write the actual code.

How does this seem?

### CODE REVIEW

**Comment by jbogard** [comment]
I like it! But would all sources be the same type? What about two disparate
sources?

**Comment by andrewm1986** [comment]
@jbogard that had never occurred to me actually

I guess conceptually there's no reason why you wouldn't want that to be the case.

I'll make sure that's one of my unit tests

**Comment by andrewm1986** [comment]
@jbogard What's your opinion on whether it should be part of IMapper as additional Merge methods or part of it's own interface, IMerge?

**Comment by jbogard** [comment]
IMapper is good, I've only really broken out the LINQ stuff into its own thing.

**Comment by jbogard** [comment]
Closing this PR for now, looks good if you want to implement!

**Pull request closed without merging**
