### PR TITLE
Add a section about conditions and resolvers

### PR DESCRIPTION
**Pull request by lbargaoanu**
Closes #2650.

### CODE REVIEW

**Comment by mrpmorris** [comment]
IMHO 2650 is far clearer. It's much easier to understand examples you are likely to write and show why they are right/wrong, and the section on the flow of events (numbered sequence) is better too.

**Comment by lbargaoanu** [comment]
@jbogard I don't see these changes in the latest docs.

**Comment by jbogard** [comment]
No? I can see them now.

**Comment by lbargaoanu** [comment]
Well, [no](http://automapperdocs.readthedocs.io/en/latest/Custom-value-resolvers.html) :) If it's just smth on my end, it doesn't matter.

**Comment by jbogard** [comment]
http://docs.automapper.org/en/stable/

:)

**Comment by lbargaoanu** [comment]
:) Yes, I never know which one of those url-s is the good one. And I'm guessing most people don't :)

**Pull request merged**
