### PR TITLE
Not needed code - nullables

### PR DESCRIPTION
**Pull request by lbargaoanu**
While testing nullable stuff I saw this code. Maybe it just needs a test.

### CODE REVIEW

**Comment by RobinHerbots** [comment]
@lbargaoanu , 

Hmm, by removing that you loose the convenience that the mapper for the non-nullable equivalent is autogenerated.

**Comment by RobinHerbots** [comment]
@lbargaoanu, 

Ok, 
... and it will solve #1669 and #1664 !

**Comment by jbogard** [comment]
So that came from 294d64bfa36bdbe142d5e5ebfa235860cf863859 but there's no failing test. I can only assume that there *was* a test failing and I added this code to make the test pass. But now the test passes without it (and I don't like that solution of automatically adding type maps - that's bad).

**Comment by lbargaoanu** [comment]
I fully agree :)

**Comment by RobinHerbots** [comment]
@jbogard ,  @lbargaoanu , 

Thx!

**Pull request merged**
