### PR TITLE
Adding ResolutionContext to IMappingAction<TSource, TDestination>.Process()

### PR DESCRIPTION
**Pull request by hallidev**
```
Adding ResolutionContext to IMappingAction<TSource, TDestination>.Process()

#3105
```

### CODE REVIEW

**Comment by lbargaoanu** [comment]
@jbogard If we go this route, next time we add a parameter, it will be another breaking change.

**Comment by hallidev** [comment]
It seems like ResolutionContext is meant to be extended to avoid breaking changes. As @jbogard mentioned in #3105, this looks like it may have just been an oversight.

I'm also struggling with what a different interface would be called to achieve the same functionality at the same spot.

**Comment by hallidev** [comment]
Why was this closed? Are there plans to address this in a different way?

**Comment by jbogard** [comment]
Yeah all the interfaces like this are supposed to have the ResolutionContext, I just missed this one.

**Comment by hallidev** [comment]
Test added

**Pull request merged**
