### PR TITLE
A passing test for #154

### PR DESCRIPTION
**Pull request by lbargaoanu**
#154

### CODE REVIEW

**Comment by jbogard** [comment]
This test fails at the command line :(

**Comment by jbogard** [comment]
I fixed it :)

**Comment by jbogard** [comment]
Merged.

**Comment by lbargaoanu** [comment]
Sometimes the tests interfere like that, but it's rather random so probably that's why I didn't see it.

**Comment by jbogard** [comment]
It's because the TDD.Net runner runs the tests in a different order than the console runner. Huzzah.

**Comment by lbargaoanu** [comment]
Beautiful :)

**Pull request closed without merging**
