### PR TITLE
Project nullable to GetValueOrDefault

### LINKED ISSUE #2082: Unable to create a map expression from Person.FKContactTypeID (System.Nullable`1[System.Int64]) to RelatedPersonDTO.FKContactTypeID (System.Int64)
I am having 2 classes and i had mapped it. 
### Source/destination types

```csharp
 public partial class Person : BaseEntity
    {
       
        [Key]
        public long PKPersonID { get; set; }

        public long? FKContactTypeID { get; set; }

        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }

        [Required]
        [StringLength(50)]
        public string LastName { get; set; }

        [StringLength(50)]
        public string MiddleName { get; set; }
}
public class RelatedPersonDTO:BaseEntity
    {
        public long PKPersonID { get; set; }

        public long FKContactTypeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

    }
```
Is there any other way apart from making public long FKContactTypeID { get; set; } to public long ?FKContactTypeID { get; set; } in RelatedPersonDTO class
### Mapping configuration

```csharp
 CreateMap<Person, RelatedPersonDTO>()              
            .ForMember(dto => dto.Mode, conf => conf.Ignore());

 baseEntity class  having mode i am ignoring it.
```

### Version: x.y.z
6.0.2 

### Expected behavior

it should map to FKContactTypeID even if it is null but iam getting issue 
Unable to create a map expression from Person.FKContactTypeID (System.Nullable`1[System.Int64]) to RelatedPersonDTO.FKContactTypeID (System.Int64)

### Actual behavior

Unable to create a map expression from Person.FKContactTypeID (System.Nullable`1[System.Int64]) to RelatedPersonDTO.FKContactTypeID (System.Int64)

### Steps to reproduce

```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
```

### PR DESCRIPTION
**Pull request by lbargaoanu**
Fixes #2082. Unless some other code should have handled it...
The IsMatch condition is fuzzy, but IsAssignableFrom doesn't help and I don't have a better idea.

### CODE REVIEW

**Comment by lbargaoanu** [comment]
Unrelated. I don't think we need to go there, but [this](https://ayende.com/blog/177377/fast-dictionary-and-struct-generic-arguments) is interesting. Maybe this will be possible out of the box eventually.

**Comment by jparaya** [comment]
Sorry for the ultra stupid question... but we have this issue now (AutoMapper 4.0.4). Is it safe to update the package to 6.2.2? (current version). Any potential issues? .Net 4.5 / MVC 5

Thanks!

**Comment by lbargaoanu** [comment]
:) http://automapperdocs.readthedocs.io/en/latest/5.0-Upgrade-Guide.html

**Comment by jparaya** [comment]
Thanks!

**Pull request merged**
