### PR TITLE
Mapping expression refactoring

### PR DESCRIPTION
**Pull request by lbargaoanu**
#805 #575 
That's the easy way to do it in my view. Explicitly separating non generic and generic implementation seemed more difficult.

### CODE REVIEW

**Comment by jbogard** [comment]
Will take a look this weekend!

**Comment by jbogard** [comment]
This ready to look at?

**Comment by lbargaoanu** [comment]
Yes. I'm sure there are bugs, but that's the main idea.

**Comment by jbogard** [comment]
Shadowing. Yisssssss

**Pull request closed without merging**
