### PR TITLE
Resolve and then map if needed

### PR DESCRIPTION
**Pull request by lbargaoanu**
I started from that test...

### CODE REVIEW

**Comment by lbargaoanu** [comment]
I think we should pass the TypeMapPlan builder around, instead all those parameters. We would just call methods on that object instead of the static method with many parameters.

**Comment by lbargaoanu** [comment]
I did it for constructor mapping. Better I think :)

**Comment by jbogard** [comment]
Started from which test?

**Comment by lbargaoanu** [comment]
When_renaming_class_constructor_parameter in Constructors.cs

**Comment by lbargaoanu** [comment]
@jbogard Can we merge this? Most fixes want to touch TypeMapPlanBuilder. If you like the idea of refactoring the mappers interface, I can do that in another PR.

**Pull request merged**
