### PR TITLE
Introduced MapperContext de-static-ization

### PR DESCRIPTION
**Pull request by mwpowellhtx**
Following up from [745](http://github.com/AutoMapper/AutoMapper/pull/745) with patched project file baselines.

### CODE REVIEW

**Comment by mwpowellhtx** [comment]
Let me know how I can help move this one along, please. Thank you.

**Comment by mwpowellhtx** [comment]
how goes this one, please? besides it appears there are now conflicts. resolve those and resubmit? thank you...

**Comment by mwpowellhtx** [comment]
what's the status of this one please?

**Comment by mwpowellhtx** [comment]
Sorry, I can't wait for you to respond to this one.

**Comment by jbogard** [comment]
Welp, I didn't get yours in but AutoMapper is de-static-ized. In hindsight, a PR this big could probably be only done by myself since I have to maintain it all, so I have to REALLY understand everything that went into it. Thanks for the effort and sorry I couldn't merge it :(

**Comment by mwpowellhtx** [comment]
I was able to do it, even though there were a couple of internal static lookups that needed attention during the process. But like you said, coordinating something like that amid smaller changes is no small feat. Thanks for looking into it.

**Pull request closed without merging**
