### PR TITLE
Implemented mapping between open generic and nongeneric or closed generic types

### PR DESCRIPTION
**Pull request by jnm2**
See #1112.

### CODE REVIEW

**Comment by jnm2** [comment]
The `openTypes` parameter is [no longer used](https://github.com/AutoMapper/AutoMapper/pull/1207/commits/687ed8ba9c021a9659bd943ca5ca50b9508d228b#diff-a040f1da85ea918e0c7af96e1cf54819R252) by the sole implementer of `IProfileConfiguration.ConfigureClosedGenericTypeMap`, so the signature could also be changed.

**Comment by jbogard** [comment]
Do you want to go ahead and change that signature? It's only used internally.

**Comment by jnm2** [comment]
Sure. I should close this PR then, right?

**Comment by jnm2** [comment]
Sure. I'm still learning the github workflow here,thanks for your patience.

**Comment by jbogard** [comment]
Nope, just push up new commits as you like

**Comment by jnm2** [comment]
Okay. I rebased earlier because the `ITypeConverter.Convert` signature changed since Feb 19 when I wrote most of the code.

Also found a [typo in Profile.cs](https://github.com/AutoMapper/AutoMapper/blob/develop/src/AutoMapper/Profile.cs#L38), but probably should be in a separate PR?

**Comment by jbogard** [comment]
Ha! No, just fix it if you like.

**Comment by jnm2** [comment]
Wow, need to edit that commit message. Type the wrong parameter name.

**Comment by jnm2** [comment]
Think I'm done. Let me know if I need to comment better or something.

**Comment by jnm2** [comment]
Think I'm done. Let me know if I need to comment better or something.
Also: this code doesn't even attempt to support generic variance or differentiate converters based on generic type parameter constraints. If that's important let me know.

**Comment by jnm2** [comment]
I see there are conflicts because of the recent work. I'm happy to rebase, just let me know.

**Comment by TylerCarlson1** [comment]
Yea you'll have to merge development in order for the PR to be merged

**Comment by jnm2** [comment]
Done.

**Pull request merged**
