### PR TITLE
Always generate typed mapping funcs

### LINKED ISSUE #1257: Dynamic mapping with nested dynamic objects
With AutoMapper 4.2.1, when mapping from a dynamic to an instance of an object, AutoMapper preserves top-level destination object properties with null/default values which do not have a corresponding property in the source object. For any nested properties which are dynamic objects, the same does not hold true. This is probably easiest to explain with an example:

```C#
    class SubSetting
    {
        public int SubTimeout { get; set; }
        public string SubColour { get; set; }
    }

    class Settings
    {
        public int Timeout { get; set; }
        public string Colour { get; set; }
        public SubSetting SubSettings { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            // The SubSettings property is another ExpandoObject.
            dynamic baseSettings = new ExpandoObject();
            baseSettings.Timeout = 1;
            baseSettings.Colour = "Red";
            baseSettings.SubSettings = new ExpandoObject();
            baseSettings.SubSettings.SubTimeout = 11;
            baseSettings.SubSettings.SubColour = "Green";

            // Create another object we will map onto the one above. 
            // Notice that we do not set a Colour or SubColour property.
            dynamic overrideSettings = new ExpandoObject();
            overrideSettings.Timeout = 2;
            overrideSettings.SubSettings = new ExpandoObject();
            overrideSettings.SubSettings.SubTimeout = 22;

            var config = new MapperConfiguration(cfg => { });
            var mapper = config.CreateMapper();

            var settings = mapper.Map<Settings>(baseSettings);

            // After this next mapping, settings.Colour == "Red" but settings.SubSettings.SubColour == null.
            mapper.Map(overrideSettings, settings);
        }
    }
```
So as mentioned in the code comments, after the second mapping `settings.SubSettings.SubColour` is null. Is this the intended behaviour for dynamic mapping? I also tried upgrading to the latest MyGet build `5.0.0-ci-1057` to see if it made a difference but that throws the following exception when making the second call to `Map()`:

```
System.InvalidCastException

Unable to cast object of type 'System.Func`4[System.Object,System.Object,AutoMapper.ResolutionContext,System.Object]' to type 'System.Func`4[System.Dynamic.ExpandoObject,TestConsoleApp.Settings,AutoMapper.ResolutionContext,TestConsoleApp.Settings]'.
```

### PR DESCRIPTION
**Pull request by lbargaoanu**
consider existing destinations when creating objects
fixes #1257

### CODE REVIEW

**Comment by lbargaoanu** [comment]
On second thought I guess this is just replicated code. I should simply make the generic version call the non-generic one.

**Comment by jbogard** [comment]
Yeah, I think so. It's something that I never got back around to.

**Comment by jbogard** [comment]
@lbargaoanu so what was the exact fix for #1257? This test is broken with a later PR and I'm trying to nail down what broke it.

**Comment by lbargaoanu** [comment]
The problem before was that two funcs with different signatures were cached for the same types. Now it's only one signature, the type safe one. Does that make sense? :)

**Comment by lbargaoanu** [comment]
The problem seems to be unrelated. It's not mapping to the passed destination object, it creates a new one. Before it called CreateObject(context).

**Pull request merged**
