### PR TITLE
Add Mapper.Reset to reset static mapping

### PR DESCRIPTION
**Pull request by jbogard**

### CODE REVIEW

**Comment by jbogard** [comment]
@lbargaoanu thoughts?

**Comment by lbargaoanu** [comment]
Do we really have to? :) I mean you solved the issue with the DI package, right?

**Comment by jbogard** [comment]
Kinda solved it, but I think these are two different issues - you can't reset the static mapping, and the ability to configure the DI extension's behavior.

If you wanted to keep the static behavior but still do `services.AddAutoMapper` then `Reset` would give you that.

**Comment by lbargaoanu** [comment]
Maybe some warning in the XML docs? Not intended for production?

**Comment by jbogard** [comment]
Sounds good.

**Pull request merged**
