### PR TITLE
Test for issue #2882

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by lbargaoanu** [comment]
I see, but that doesn't help much, because we're not going to reference Castle.Core. We need a repro without it. What is it about that proxy that causes the issue?

**Comment by jogibear9988** [comment]
I don't know what is the issue. 
Caste Core is only referenced by the tests, not by the main package. 

But if we find out why it does not work, maybe I can create a test without castle core. Can you help with that? Code worked in v7 without problems. And I think it's a common scenario to use automapper with proxy objects

**Comment by lbargaoanu** [comment]
I have no idea why that proxy is special. Once we have a repro without Castle, I'll take a look.

**Comment by jogibear9988** [comment]
Can't you fetch my fork and run the code? I've no Idea where to look!

**Comment by jogibear9988** [comment]
image

Parameter.IsOptional is false,
Parameter.ParameterType is of IInterceptor[]
SourceMebers List is empty

**Comment by jogibear9988** [comment]
Proxy Type, has a Field of Name "__interceptors"

image

**Comment by jogibear9988** [comment]
@lbargaoanu I think I found the issue.

Automapper creates a ConstructorParameter without a Name. And your Code in 
    
     if (string.IsNullOrEmpty(nameToSearch))
                return true;

Returns true, so a it says a matching member is found (but don't know why it worked in V7)

**Comment by lbargaoanu** [comment]
I'm not sure I understand. But if you do, a PR is welcome. Of course that needs a failing test without Castle.

**Comment by jogibear9988** [comment]
Failing test without castle...

**Comment by lbargaoanu** [comment]
OK, so you mean Castle creates a ConstructorParameter without a name. You wrote AM and that doesn't make much sense.

**Comment by jogibear9988** [comment]
Yes, castle creates a Constructor Parameter without a Name.

Look at my updated Pull Req. It now does not use Castle.Core Any more and fails with the same error!

**Comment by lbargaoanu** [comment]
But you do know that AM can create proxies for you, including implementing INotifyPropertyChanged.

**Comment by jogibear9988** [comment]
I've seen it. But this is existing Code, and I cannot change it atm!
And it worked with the previous Version, so I think we should look that the new one does not break existing Code.
Is there anything more I could test/help?

**Comment by lbargaoanu** [comment]
This is not the first time this happens. And I'm pretty sure it will happen again. I mean, parameters without names? Really? :) I've opened a PR, but this is not a good place to be. I cringe when I look at that test.

**Comment by jogibear9988** [comment]
Why should a Name in generated Code be needed?
I only map to existing Instances created by Castle Dynmaic Proxy, so Automapper don't need to map anything of the Constructor.
Is there no way, so I could tell that it should only Map Proiperties? (I thought this is/was the default)

**Comment by jogibear9988** [comment]
And shouldn't in DefaultMember the lines

            if (string.IsNullOrEmpty(nameToSearch))
                return true;

also be removed?

**Comment by lbargaoanu** [comment]
You can disable constructor mapping (by default it's enabled). There is a method on the configuration. I've tried removing that code in your branch and it didn't go well :) That's why I started again from scratch.

**Pull request closed without merging**
