### PR TITLE
Adding ability to configure the member list to validate; closes #2402

### LINKED ISSUE #2402: 6.2.0 Broke Conventions-Based Mappings With Missing Target Members
### Version: 6.2.0

This works fine in v6.1.1

### Expected behavior

The mapping happens successfully and `FooViewModel.Extra` is `null`

### Actual behavior

Exception:

```
AutoMapper.AutoMapperConfigurationException : 
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
================================================================
Foo -> FooViewModel (Destination member list)
AutoMapper.Bug.Class2+Foo -> AutoMapper.Bug.Class2+FooViewModel (Destination member list)

Unmapped properties:
Extra

```

### Steps to reproduce

```csharp
public class Foo
{
    public string Bar { get; set; }
}

public class FooViewModel
{
    public string Bar { get; set; }
    public string Extra { get; set; }
}

public class ViewModelConvention : Profile
{
    /// <summary>
    /// Initialises a new instance of the <see cref="ViewModelConvention"/> class.
    /// </summary>
    public ViewModelConvention()
    {
        AddConditionalObjectMapper().Where((source, dest) => dest.Name == source.Name + "ViewModel");
    }
}

[Fact]
public void TestMappingWithMissingTargetProperty()
{
    Mapper.Initialize(cfg => cfg.AddProfile<ViewModelConvention>());

    var result = Mapper.Map<FooViewModel>(new Foo { Bar = "Baz" });

    result.Bar.Should().Be("Baz");
}
```

### PR DESCRIPTION
**Pull request by jbogard**

### CODE REVIEW

**Comment by jbogard** [comment]
@lbargaoanu thoughts?

**Comment by lbargaoanu** [comment]
I guess it would make more sense if it were specified somewhere closer to where the map is defined. I guess it doesn't apply to the regular maps.

**Comment by lbargaoanu** [comment]
Took a quick look at the code and it seems it's the same property as for the regular maps, so it fits in IMappingExpression. My first point remains. I guess most people don't care, they don't want validation anyway.

**Comment by jbogard** [comment]
Yeah, I looked at changing the conventions API itself but that'd be a breaking change to `IConditionalObjectMapper` so this seems to be the most straightforward way.

I don't use conventions so I don't really know what would be appropriate there.

**Comment by TylerCarlson1** [comment]
For Conventions I usually don't want validation.  Conventions are a little less lazy then CreateMissingTypeMaps, but it's still pretty lazy.

**Comment by jbogard** [comment]
Why wouldn’t you want validation?

**Comment by TylerCarlson1** [comment]
I am accustomed to the expected case of #2402.  It's simple it just works and I don't have to think about missing property maps.  If they don't match then I didn't want them mapped, and I would make sure I would have the ones I wanted.

**Pull request merged**
