### PR TITLE
Suppress generic constraint exceptions in GetPublicNoArgExtensionMethods

### PR DESCRIPTION
**Pull request by stephentoub**
GetPublicNoArgExtensionMethods tries to instantiate arbitrary generic methods with arbitrary type arguments, which can fail if those arguments don't meet any constraints defined on the generic parameters. Automapper isn't doing the required checking for constraint validation today, resulting in exceptions escaping; multiple existing Automapper unit tests fail on .NET 7 as a result.  This works around it by eating the ArgumentException that comes from MakeGenericMethod (there's no exposed compatibility-checking function, and so while not usually recommended, the most reliable thing here is to simply catch the errors stemming from the validation MakeGenericMethod performs).

Fixes https://github.com/AutoMapper/AutoMapper/issues/3988

### CODE REVIEW

**Comment by jbogard** [comment]
Related feature request to not have to do this exception silliness:

https://github.com/dotnet/runtime/issues/28033

le sigh

**Review by jbogard — APPROVED** [review]

**Comment by lbargaoanu** [comment]
Maybe we should simply skip all methods with generic constraints.

**Comment by PriyaPurkayastha** [comment]
@jbogard @lbargaoanu we (.NET team) would like to collaborate with you on this issue. We recognize that AutoMapper library is used by many applications, and it is important for us that these applications continue to work with .NET 7. Can you please contact us on dotnet@microsoft.com? Thanks!

**Comment by lbargaoanu** [comment]
I'm on vacation for the next two weeks :)
@jbogard If someone is interested in speeding up AM configuration, the first thing to do is to disable the [expensive stuff](https://gist.github.com/lbargaoanu/9948bf66d452ba6b816252f9965143ee). That's the configuration I've profiled until now. But it's on by default. So I've tried to minimize the damage (in my branch). Mainly by calling `MakeGenericMethod` only when the extension method actually matches a destination name.

**Comment by PriyaPurkayastha** [comment]
Thanks @lbargaoanu. We wanted to get some information as follows:
1. When is the planned release date for AutoMapper 11.0.2 which contains this fix that Stephen submitted?
2. We found that several apps in our AppCompat lab use older versions of AutoMapper. Can you please let us know what your Servicing plans look like? Do you normally service previous AutoMapper major/minor versions, or would your customers need to pick up the latest version when they use .NET 7? If you do service previous releases, what can we do to get the fix in those releases as well?

.NET 7 GA is this November, so we have a couple of weeks to evaluate the options. Have a great vacation! We look forward to hearing back from you.

**Pull request merged**
