### PR TITLE
Initialize with profile bug 565

### PR DESCRIPTION
**Pull request by lbargaoanu**
#565

### CODE REVIEW

**Comment by jbogard** [comment]
Sooooo I don't like the implementation. If you're using a profile you should have more than one, otherwise just use cfg.CreateMap.

**Comment by lbargaoanu** [comment]
Roger :)

**Comment by jbogard** [comment]
I think this is more of a documentation issue to be more explicit. Long term it's more of an API issue.

**Comment by lbargaoanu** [comment]
OK, so better to close it for now?

**Comment by jbogard** [comment]
Yep!

**Pull request closed without merging**
