### PR TITLE
Use non prerelease versions of System-packages

### PR DESCRIPTION
**Pull request by Tasteful**
Use non prerelease versions of System-packages from https://www.myget.org/gallery/aspnetrelease

### CODE REVIEW

**Comment by lbargaoanu** [comment]
This doesn't apply to netstandard1.1?

**Comment by Tasteful** [comment]
@lbargaoanu Correct that it's not support netstandard 1.1. The dependency System.Collections.Specialized is only supporting the following TFM
```
.NETFramework 4.6: 4.6.0.0
.NETStandard 1.3: 1.3.0.0
MonoAndroid 1.0: 1.0.0.0
MonoTouch 1.0: 1.0.0.0
Xamarin.iOS 1.0: 1.0.0.0
Xamarin.Mac 2.0: 2.0.0.0
Xamarin.TVOS 1.0: 1.0.0.0
Xamarin.WatchOS 1.0: 1.0.0.0
```
https://www.myget.org/feed/aspnetrelease/package/nuget/System.Collections.Specialized/4.0.1
I'm not sure if this is the final-final package of the System.Collections.Specialized.

**Comment by Tasteful** [comment]
@lbargaoanu It was I that read wrong. the System.Collections.Specialized was not used in netstandard1.1 so I added that back. (copy/paste misstake)

**Comment by jbogard** [comment]
Thanks! RTM packages dropped today, so I just targeted those. Thanks for the PR!

**Pull request closed without merging**
