### PR TITLE
Remove dynamic maps

### LINKED ISSUE #3063: Remove dynamic maps
After having these out for a bit, is there any real value to them? They seem to cause more problems than they solve.

I don't use them, none of our teams do, and they go against the [original design philosophy](https://jimmybogard.com/automappers-design-philosophy/).

This would mean convention-based stuff would go too, to be replaced with scanning-based conventions. The only late-created maps I'd want are closing generic types.

- **Deprecate CreateMissingTypeMaps and change the default to false #3102**

### PR DESCRIPTION
**Pull request by jbogard**
Removes all means of creating dynamic/inline maps. Fixes #3063

### CODE REVIEW

**Comment by lbargaoanu** [comment]
I don't think deleting tests is a good idea. Because we still have dynamic mapping with generics. And most of the issues apply. Especially concurrency issues and recursive mapping. I'm not saying it's trivial to rewrite those tests with generics, but I think it's time well spent.

**Comment by jbogard** [comment]
We've got a test for the generics thing already I thought? The same file, `ResolveWithGenericMap`.

**Comment by lbargaoanu** [comment]
That's true. But for example ResolveTypeMapThreadingIssues has no generic counterpart, right? I think we should check every case.

**Comment by lbargaoanu** [comment]
ConventionCreateMapsWithCircularReference is another case.

**Comment by jbogard** [comment]
I dunno about the convention one - that would resolve to `Mapper.Map`

**Comment by lbargaoanu** [comment]
So we're talking about ConventionCreateMapsWithCircularReference. Yes, it would just call Map, but it would have to create those closed generics maps that reference each other. Or I'm completely missing your point :)

**Comment by jbogard** [comment]
@lbargaoanu added back the tests with generic flavor.

**Comment by lbargaoanu** [comment]
Dynamic_constructor_mapping. Maybe this one is too much, I don't know :)

**Comment by jbogard** [comment]
OK added one test for that last one.

LAST ONE

**Comment by lbargaoanu** [comment]
All right :) So, maybe skip the failing tests at this time? :)

**Comment by jbogard** [comment]
Sigh

**Comment by jbogard** [comment]
Ah these look like proper failing tests - it's generic types containing generic members.

**Comment by lbargaoanu** [comment]
So, valuable tests, I guess :)

**Comment by jbogard** [comment]
There's still a failing test but I commented it out

**Comment by lbargaoanu** [comment]
I think skipping it is better, as it's less likely that we'll ignore it.

**Comment by jbogard** [comment]
Can’t, it’s the config validation

**Pull request merged**
