### PR TITLE
Validating constructor mapping as part of configuration validation

### LINKED ISSUE #1456: AutoMapper fails to map class with non-default constructor
When upgrading to version 5.0.0 (from nuget) I found this strange bug. 

I have two classes with one property each with different names. The target class has two constructors one default and one that take a value to fill the property. The parameter has the same name as the property. AutoMapper fail to map this this example. See unit test below. 

```
    [TestClass]
    public class AutoMapperBug
    {
        [TestMethod]
        public void Test()
        {
            Mapper.Initialize(config =>
            {
                config.CreateMap<ClassA, ClassB>().ForMember(dest => dest.PropertyB, opt => opt.MapFrom(src => src.PropertyA));
            });

            ClassA classA = new ClassA { PropertyA = "test" };
            ClassB classB = Mapper.Map<ClassB>(classA);
            Assert.AreEqual("test", classB.PropertyB);
        }
    }

    public class ClassA
    {
        public string PropertyA { get; set; }

    }

    public class ClassB
    {
        public ClassB()
        {
        }

        public ClassB(string propertyB)
        {
            PropertyB = propertyB;
        }

        public string PropertyB { get; set; }
    }
```

### LINKED ISSUE #1457: AutoMapper 5.0.0 introduces runtime errors that AssertConfigurationIsValid doesn't catch
I mentioned in #1455 that I have two issues since upgrading to 5.0.0. Here's the other one.

There are quite a lot of mappings in our project that are, by the standards of 5.0.0, pretty broken. For one thing, there are static calls to `Mapper.Map()` inside the configurations; those I'm working on removing.

But there are also mapping targets which have private constructors written explicitly to allow AutoMapper 2.2.1 to construct the objects and then map properties from some DTO. Many of these now throw runtime errors at mapping time with the pretty uninformative error message

> System.ArgumentException: MyProject.Foo.DestinationType needs to have a constructor with 0 args or only optional args

Since these errors aren't discovered by the configuration verification, we're pretty screwed; we don't have test coverage that excercises all possible mappings, so we won't find all of these until someone stumbles on them in production. Unless this can be resolved, this is pretty much a dealbreaker for our upgrade :(

### PR DESCRIPTION
**Pull request by jbogard**
Fixes #1456 
Fixes #1457

### CODE REVIEW

**Comment by lbargaoanu** [comment]
What if they pass in the destination? :)

**Comment by lbargaoanu** [comment]
Or any other case when AM doesn't create the destination object.

**Comment by jbogard** [comment]
¯\_(ツ)_/¯

**Comment by jbogard** [comment]
So I guess the other case would be UseDestinationValue?

**Comment by jbogard** [comment]
The only way you could get around this really is to add an option to ignore constructor validation I think.

**Comment by lbargaoanu** [comment]
Exactly :)

**Comment by lbargaoanu** [comment]
But the default should be not to validate in my view.

**Comment by lbargaoanu** [comment]
In the other PR I was thinking about [this](https://github.com/AutoMapper/AutoMapper/blob/781f0533f34564a6af3b8a8654cf14e9f2e4f73b/src/AutoMapper/Execution/TypeMapPlanBuilder.cs#L238). Forgot about UseDestinationValue :)

**Comment by jbogard** [comment]
I made the assumption that normally people don't use UseDestinationValue or
mapping to an existing object. The default is to map to the ctors, so the
expression generated has that "throw" in it.

**Comment by lbargaoanu** [comment]
I guess we'll see :)

**Pull request merged**
