### PR TITLE
Mapping dynamic objects with lists of dynamic objects

### PR DESCRIPTION
**Pull request by HubertoKusters**
Added the ability to map dynamic objects with lists of dynamic objects to class instances  and back again.
Addresses issue #1836

### CODE REVIEW

**Comment by lbargaoanu** [comment]
I'm sorry, but this code is arbitrary. I'm sure it solves your particular case, but it doesn't really make sense in the general case.

**Comment by HubertoKusters** [comment]
What is necessary in your view to make it not so arbitrary? I try to understand what is wrong with this solution?

**Comment by jbogard** [comment]
In that it only does a collection. Perhaps instead it should defer to the context Mapper?

**Comment by lbargaoanu** [comment]
This is a corner case anyway, you can simpy replace the dynamic mappers with your versions in the mappers collection.

**Comment by HubertoKusters** [comment]
I agree with @jbogard that it only handles a collection. I think it is reasonable to assume that the handling of arrays and dictionaries should be included as well. I did not do that jet, because I was not sure if my solution is the way to go. But I had to give some implementation to get this started.

I do not agree with @lbargaoanu that it is an edge case. The dynamic mapper is capable of mapping A to X and B to Y. But it is not capable to map A (containing a list of B) to X (containing a list of Y) and that is short-coming I try to implement. 

I know that you one can implement a custom mapper and insert it in the mappers collection. But doing so would require duplicating a lot of your utility extensions, which I automatically have to my disposal when implementing this within AutoMapper.

That being said I totally agree that a well-used library like the AutoMapper should not be polluted with code the has no place in it. If you think that this is the case, I will retract the pull-request. ;)

**Comment by lbargaoanu** [comment]
AM can map it if you type it object or if you don't mix dynamic with typed members. So of course it's an edge case :) And it's not obvious why AM would prefer dynamic instead of the type you specify. I'm sure some people would find that strange.

**Pull request closed without merging**
