### PR TITLE
DynamicMap threading issues

### PR DESCRIPTION
**Pull request by lbargaoanu**
I broke the DynamicMap threading test with #628.
I found three errors which I put [here](https://github.com/lbargaoanu/AutoMapper/blob/9ba3783c11b1eaebc36e7750fc09e489ad7e0316/src/UnitTests/Bug/MultiThreadingIssues.cs#L257).
Obviously this kind of test is not exactly reliable, but I did try :).
Maybe there is a more elegant fix, but regardless, I think it's difficult to see what happens.
Perhaps separating DynamicMap in a different method would be a good idea, because Map doesn't care about the threading issues (something might happen with generic mappings, but I don't have a failing test).
Also, maybe coarser grained locking would make the code easier to understand. As in wrapping the "find mapper" part of DynamicMap in a lock for the type pair, or something like that.

### CODE REVIEW

**Comment by jbogard** [comment]
Hmmm I have 4 failing tests with this fix:

```
------- Testing Assembly AutoMapper.UnitTests.Net4.dll ------

Test 'AutoMapper.UnitTests.ConfigurationValidation.When_testing_a_dto_with_matching_member_names_but_mismatched_types.Should_fail_a_configuration_check' failed: Should.Core.Exceptions.NotNullException
Assert.NotNull() Failure
   at AutoMapper.UnitTests.AssertionExtensions.ShouldBeThrownBy(Type exceptionType, ThrowingAction action) in C:\dev\automapper\src\UnitTests\AssertionExtensions.cs:line 48
   at AutoMapper.UnitTests.ConfigurationValidation.When_testing_a_dto_with_matching_member_names_but_mismatched_types.Should_fail_a_configuration_check() in C:\dev\automapper\src\UnitTests\ConfigurationValidation.cs:line 124

Test 'AutoMapper.UnitTests.ConfigurationValidation.When_testing_a_dto_with_array_types_with_mismatched_element_types.Should_fail_a_configuration_check' failed: Should.Core.Exceptions.NotNullException
Assert.NotNull() Failure
   at AutoMapper.UnitTests.AssertionExtensions.ShouldBeThrownBy(Type exceptionType, ThrowingAction action) in C:\dev\automapper\src\UnitTests\AssertionExtensions.cs:line 48
   at AutoMapper.UnitTests.ConfigurationValidation.When_testing_a_dto_with_array_types_with_mismatched_element_types.Should_fail_a_configuration_check() in C:\dev\automapper\src\UnitTests\ConfigurationValidation.cs:line 250

Test 'AutoMapper.UnitTests.ConfigurationValidation.When_testing_a_dto_with_list_types_with_mismatched_element_types.Should_fail_a_configuration_check' failed: Should.Core.Exceptions.NotNullException
Assert.NotNull() Failure
   at AutoMapper.UnitTests.AssertionExtensions.ShouldBeThrownBy(Type exceptionType, ThrowingAction action) in C:\dev\automapper\src\UnitTests\AssertionExtensions.cs:line 48
   at AutoMapper.UnitTests.ConfigurationValidation.When_testing_a_dto_with_list_types_with_mismatched_element_types.Should_fail_a_configuration_check() in C:\dev\automapper\src\UnitTests\ConfigurationValidation.cs:line 284

Test 'AutoMapper.UnitTests.ConfigurationValidation.When_testing_a_dto_with_mismatched_custom_member_mapping.Should_fail_a_configuration_check' failed: Should.Core.Exceptions.NotNullException
Assert.NotNull() Failure
   at AutoMapper.UnitTests.AssertionExtensions.ShouldBeThrownBy(Type exceptionType, ThrowingAction action) in C:\dev\automapper\src\UnitTests\AssertionExtensions.cs:line 48
   at AutoMapper.UnitTests.ConfigurationValidation.When_testing_a_dto_with_mismatched_custom_member_mapping.Should_fail_a_configuration_check() in C:\dev\automapper\src\UnitTests\ConfigurationValidation.cs:line 385

```

**Comment by lbargaoanu** [comment]
Maybe I don't have those tests :) I'll check.

**Comment by TylerCarlson1** [comment]
Actually @jbogard I get those exact same errors from development stream.  It looks like it has nothing to do with the PR.

**Comment by lbargaoanu** [comment]
I tend to agree. Now I'm behind develop and some change is related to configuration validation.

**Comment by jbogard** [comment]
Yeah I broke the build. Fixing now.

**Comment by jbogard** [comment]
Merged.

**Pull request closed without merging**
