### PR TITLE
AutoMap attribute configuration options

### PR DESCRIPTION
**Pull request by gmilani**
Adding the following configuration options by the AutoMap attribute
- ConstructUsingServiceLocator
- MaxDepth
- PreserveReferences
- DisableCtorValidation
- TypeConverter

#2936

### CODE REVIEW

**Comment by jbogard** [comment]
Fixes #2936

**Comment by lbargaoanu** [comment]
@jbogard This was on the wrong branch.

**Comment by jbogard** [comment]
Ugh

**Comment by gmilani** [comment]
Hi, @jbogard 
I read in the contribution guidelines that you accept PRs only in the branch dev. I thought this was the current dev branch. Sorry about that
Should I open a PR to the master branch?

**Comment by jbogard** [comment]
Yes thanks! We’ll fix the guidelines.

**Pull request merged**
