### PR TITLE
Testing FastExpressionCompiler

### PR DESCRIPTION
**Pull request by jbogard**
Seems slightly slower

### CODE REVIEW

**Comment by lbargaoanu** [comment]
But how did you test, with CompileMappings and some large model?

**Comment by dadhi** [comment]
Mmm, code looks Ok. What's VisualStudioProfiler? Can we measure with BDN?

**Comment by jbogard** [comment]
Sure!

**Comment by dadhi** [comment]
Also does it really hit the fast path? Can you try `CompileFast(true)` and check if it returns `null`?

**Comment by jbogard** [comment]
Looks about a 30% improvement in compilation speed

**Comment by jbogard** [comment]
@dadhi on my local machine :P

**Pull request closed without merging**
