### PR TITLE
Order interfaces by type hierarchy; closes #1016 closes #1036

### LINKED ISSUE #1016: Incorrect Mapping Inheritance with existing destination object
I automapping an interface in other new --> it's OK (find GOOD JOB in source code)
I automapping an interface in other existing --> it's NOT OK (find BAD JOB in source code)

here is my simple example source code to view the problem : 

```
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using AutoMapper;

namespace UIModelTest
{
    [TestClass]
    public class TestAutomapper
    {
        [TestMethod]
        public void automapperTest()
        {
            Mapper.CreateMap<iclass1, iclass1DTO>().Include<iclass2, iclass2DTO>().Include<iclass3, iclass3DTO>().Include<iclass4, iclass4DTO>();
            Mapper.CreateMap<iclass2, iclass2DTO>();
            Mapper.CreateMap<iclass3, iclass3DTO>();
            Mapper.CreateMap<iclass4, iclass4DTO>().ConstructUsing((ResolutionContext rc) => new class4DTO());
            Mapper.Configuration.Seal();
            Mapper.AssertConfigurationIsValid();

            iclass4 bo = new class4() ;
            bo.prop1 = "PROP1";
            bo.prop2 = "PROP2";
            bo.prop3 = "PROP3";
            bo.prop4 = "PROP4";
            iclass4DTO dto = new class4DTO();

            // BAD JOB : HS
            Mapper.Map<iclass4, iclass4DTO>(bo, dto);

           // GOOD JOB : OK !! 
            iclass4DTO dto2 = Mapper.Map<iclass4, iclass4DTO>(bo);
        }
    }

    public abstract class class1 : iclass1
    {
        public string prop1 { get;set;}
    }

    public class class2 : class1, iclass2
    {
        public string prop2 { get; set; }
    }

    public class class3 : class2, iclass3
    {
        public string prop3 { get; set; }
    }

    public class class4 : class3, iclass4
    {
        public string prop4 { get; set; }
    }

    public abstract class class1DTO : iclass1DTO
    {
        public string prop1 { get; set; }
    }

    public class class2DTO : class1DTO, iclass2DTO
    {
        public string prop2 { get; set; }
    }

    public class class3DTO : class2DTO, iclass3DTO
    {
        public string prop3 { get; set; }
    }

    public class class4DTO : class3DTO, iclass4DTO
    {
        public string prop4 { get; set; }
    }

    public interface iclass1
    {
        string prop1 { get; set; }
    }

    public interface iclass2 : iclass1
    {
        string prop2 { get; set; }
    }

    public interface iclass3 : iclass2
    {
        string prop3 { get; set; }
    }

    public interface iclass4 : iclass3
    {
        string prop4 { get; set; }
    }

    public interface iclass1DTO
    {
        string prop1 { get; set; }
    }

    public interface iclass2DTO : iclass1DTO
    {
        string prop2 { get; set; }
    }

    public interface iclass3DTO : iclass2DTO
    {
        string prop3 { get; set; }
    }

    public interface iclass4DTO : iclass3DTO
    {
        string prop4 { get; set; }
    }
}
```
Thank you in advance for your help

Best regards

Christophe

### LINKED ISSUE #1036: Incorrect mapping when source implement multiple interfaces
When source class implement several interfaces, it is possible that least-derived interface would be used for mapping.
Here is an example:
```
using AutoMapper;
using NUnit.Framework;

namespace AutoMapperSamples
{
    namespace Interfaces
    {
        [TestFixture]
        public class MappingToInterfaces2
        {
            [Test]
            public void TestMultipleInterfaceMapping()
            {
                var from = new MapFrom
                {
                    Element = new MapFromElementDerived { Prop = "qwerty", Prop2 = "asdf" }
                };
                Mapper.Initialize(
                    cfg =>
                    {
                        cfg.CreateMap<IMapFrom, MapTo>();
                        cfg.CreateMap<IMapFromElement, IMapToElementWritable>()
                        .Include<IMapFromElementDerived, IMapToElementWritableDerived>();

                        cfg.CreateMap<IMapFromElementDerived, IMapToElementWritableDerived>()
                            .ConstructUsing((ResolutionContext item) => new MapToElementDerived());

                        cfg.Seal();
                    });
                Mapper.AssertConfigurationIsValid();

                var result = Mapper.Map<MapTo>(from);
                var element = (IMapToElementWritableDerived)result.Element;

                Assert.AreEqual(element.Prop2, "asdf");
            }
        }

        public interface IMapFrom
        {
            IMapFromElement Element { get; }
        }

        public class MapFrom : IMapFrom
        {
            public MapFromElement Element { get; set; }
            IMapFromElement IMapFrom.Element => Element;
        }


        public interface IMapFromElement
        {
            string Prop { get; }
        }

        public interface IMapFromElementDerived : IMapFromElement
        {
            string Prop2 { get; }
        }

        public interface IMapFromElement2 : IMapFromElement
        {
        }

        public interface IMapFromElementDerived2 : IMapFromElementDerived, IMapFromElement2
        {
        }

        public class MapFromElement : IMapFromElement
        {
            public string Prop { get; set; }
        }


        public class MapFromElementDerived : MapFromElement, IMapFromElementDerived2
        {
            public string Prop2 { get; set; }
        }


        public class MapTo
        {
            public IMapToElementWritable Element { get; set; }
        }

        public interface IMapToElementWritable : IMapFromElement
        {
            new string Prop { get; set; }
        }

        public interface IMapToElementWritableDerived : IMapFromElementDerived, IMapToElementWritable
        {
            new string Prop2 { get; set; }
        }

        public abstract class MapToElement : IMapToElementWritable
        {
            public string Prop { get; set; }
        }

        public class MapToElementDerived : MapToElement, IMapToElementWritableDerived
        {
            public string Prop2 { get; set; }
        }
    }
}
```

Here, instead of creation MapToElementDerived mapper create IMapToElementWritable proxy.

### PR DESCRIPTION
**Pull request by lbargaoanu**

### CODE REVIEW

**Comment by iskiselev** [comment]
You omitted interface comparing. GetInterfaces should not return more derived interface before less derived. It still breaks with:
```
    namespace Interfaces
    {
        [TestFixture]
        public class MappingToInterfaces2
        {
            [Test]
            public void TestMultipleInterfaceMapping()
            {
                var from = new MapFrom
                {
                    Element = new MapFromElementDerived { Prop = "qwerty", Prop2 = "asdf" }
                };
                var mapperConfig = new MapperConfiguration(cfg =>
                    {
                        cfg.CreateMap<IMapFrom, MapTo>();
                        cfg.CreateMap<IMapFromElement, IMapToElementWritable>()
                        .Include<IMapFromElementDerived, IMapToElementWritableDerived>();

                        cfg.CreateMap<IMapFromElementDerived, IMapToElementWritableDerived>()
                            .ConstructUsing((ResolutionContext item) => new MapToElementDerived());
                        cfg.CreateMap<IMapFromElementDerived, MapToElementDerived>();

                        //cfg.Seal();
                    });
                mapperConfig.AssertConfigurationIsValid();
                var mapper = mapperConfig.CreateMapper();

                var result = mapper.Map<MapTo>(from);
                var element = (IMapToElementWritableDerived)result.Element;

                Assert.AreEqual(element.Prop2, "asdf");
            }
        }

        public interface IMapFrom
        {
            IMapFromElement Element { get; }
        }

        public class MapFrom : IMapFrom
        {
            public MapFromElement Element { get; set; }
            IMapFromElement IMapFrom.Element => Element;
        }


        public interface IMapFromElement
        {
            string Prop { get; }
        }

        public interface IMapFromElementDerived : IMapFromElement
        {
            string Prop2 { get; }
        }

        public interface IMapFromElement2 : IMapFromElement
        {
        }

        public interface IMapFromElementDerived2 : IMapFromElementDerived, IMapFromElement2
        {
        }

        public class MapFromElement : IMapFromElement
        {
            public string Prop { get; set; }
        }


        public class MapFromElementDerived : MapFromElement, IMapFromElementDerived2
        {
            public string Prop { get; set; }
            public string Prop2 { get; set; }
        }


        public class MapTo
        {
            public IMapToElementWritable Element { get; set; }
        }

        public interface IMapToElementWritable : IMapFromElement
        {
            new string Prop { get; set; }
        }

        public interface IMapToElementWritableDerived : IMapFromElementDerived, IMapToElementWritable
        {
            new string Prop2 { get; set; }
        }

        public abstract class MapToElement : IMapToElementWritable
        {
            public string Prop { get; set; }
        }

        public class MapToElementDerived : MapToElement, IMapToElementWritableDerived
        {
            public string Prop2 { get; set; }
        }
    }
```

(I've added Prop to MapFromElementDerived)

**Comment by lbargaoanu** [comment]
I don't think it's worth the extra complexity.

**Comment by iskiselev** [comment]
In this PR you don't compare interface between each other (what I have initially done in #1037).
So, in some situations, even if `IDerived:IBase`, `IBase` will still be chosen for mapping instead of `IDerived`.
This PR also drops marker interface support (probably they are not necessary for mappings at all) and may prefer interface over class (previously mapping over class was used before attempt to use mapping over interface).

**Comment by jbogard** [comment]
I took #1050

**Pull request closed without merging**
