### PR TITLE
Add PreCondition overload that takes source and ResolutionContext as parameters

### LINKED ISSUE #2251: Add PreCondition overload
In IMemberConfigurationExpression there is a PreCondition method that passes source, and there is a PreCondition method that passes ResolutionContext, however there isn't one that passes both.

____

Internally, in the MemberConfigurationExpression implementation, both the existing PreCondition methods set an expression property that takes both the source and ResolutionContext as parameters.

It also appears that TypeMapPlanBuilder passes both parameters to the internal PreCondition expression property.

So I don't think much would need to change to implement this.

### PR DESCRIPTION
**Pull request by ESPNSTI**
Added an overload to PreCondition that had both TSource and ResolutionContext as parameters.
Closes #2251.

### CODE REVIEW

**Comment by lbargaoanu** [comment]
The test is missing.

**Comment by ESPNSTI** [comment]
There's no test for the ResolutionContext overload either. :)

I'll see what I can do.

**Comment by lbargaoanu** [comment]
Maybe it's GitHub's fault, but it would be nice if you could fix the diff.

**Comment by ESPNSTI** [comment]
I'm not sure what's going on, I thought I had set autocrlf to false.
I'll check and see if I can fix it.
Some of the files seem to have inconsistent line endings it seems.

**Pull request merged**
