### PR TITLE
ProjectTo does not load expanded child collections.

### LINKED ISSUE #3380: ProjectTo child collections explicit expansion.
I created a PR #3379 for this issue.

In `\AutoMapper\src\IntegrationTests\ExplicitExpansion\ExpandCollections.cs`:

Change:
```c#
        protected override MapperConfiguration Configuration => new MapperConfiguration(cfg =>
        {
            cfg.CreateMap<Category, CategoryDto>();
            cfg.CreateMap<TrainingCourse, TrainingCourseDto>();
            cfg.CreateMap<TrainingContent, TrainingContentDto>().ForMember(c => c.Category, o => o.ExplicitExpansion());
        });
```

to

```c#
        protected override MapperConfiguration Configuration => new MapperConfiguration(cfg =>
        {
            cfg.CreateMap<Category, CategoryDto>();
            cfg.CreateMap<TrainingCourse, TrainingCourseDto>().ForMember(c => c.Content, o => o.ExplicitExpansion());
            cfg.CreateMap<TrainingContent, TrainingContentDto>().ForMember(c => c.Category, o => o.ExplicitExpansion());
        });
```

This works against the latest commit.

### PR DESCRIPTION
**Pull request by BlaiseD**
Fixes #3380.

### CODE REVIEW

**Comment by lbargaoanu** [comment]
Please undo the test change and add a new minimal test.

**Comment by BlaiseD** [comment]
ok -  will do.  I thought about that but it looked as though that was the purpose of the current test.

**Comment by lbargaoanu** [comment]
Of course you can copy the existing one if it's close enough :)

**Comment by BlaiseD** [comment]
New test added @lbargaoanu

**Comment by BlaiseD** [comment]
Thanks for reviewing.

**Pull request merged**
