### PR TITLE
target net5.0

### PR DESCRIPTION
**Pull request by anwarjaved**
Add net5.0 in target framework

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AutoMapper/AutoMapper?pullRequest=3710) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AutoMapper/AutoMapper?pullRequest=3710) before we can accept your contribution.<br/><br/>:x: anwarjaved [sign now](https://cla.dotnetfoundation.org/AutoMapper/AutoMapper?pullRequest=3710)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AutoMapper/AutoMapper?pullRequest=3710) it.</sub>

**Comment by lbargaoanu** [comment]
There is no need for that.

**Comment by anwarjaved** [comment]
I was trying it in .net 5.0 project and it wasn't working

**Comment by lbargaoanu** [comment]
Our tests run on 5.0, so you must be doing smth wrong.

**Comment by anwarjaved** [comment]
I was trying to install package and visual studio still asking me to install package was getting error in project related to autofac

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by anwarjaved** [comment]
yes but .net 5.0 is new standard for future projects
[https://visualstudiomagazine.com/articles/2020/09/16/net-standard-future.aspx](https://visualstudiomagazine.com/articles/2020/09/16/net-standard-future.aspx)

**Comment by anwarjaved** [comment]
It seems Microsoft.DotNet.ApiCompat not exists on nuget anymore

**Comment by anwarjaved** [comment]
image

**Pull request closed without merging**
