### PR TITLE
Complex types bug 925

### PR DESCRIPTION
**Pull request by lbargaoanu**
#925

### CODE REVIEW

**Comment by jbogard** [comment]
Maybe an attribute instead of a marker interface since we have the IgnoreMap attribute already?

**Comment by lbargaoanu** [comment]
Well, yes, but an attribute is more expensive to query and I was tempted to cache it somehow. Decisions, decisions :)

**Comment by jbogard** [comment]
If someone is using EF already, is there an existing ComponentModel attribute they can use? I'm also leaning attributes because it's what EF folks seem to be more OK with than marker interfaces

**Comment by lbargaoanu** [comment]
Spot on :) But it lives in System.ComponentModel.DataAnnotations.dll. Do we want to reference that? :)

**Comment by jbogard** [comment]
Only if it's really available for all platforms. I try not to have compile directives mixed inside a file, and instead scope it to the entire file. This one might be tough to just put in one tiny spot.

**Comment by lbargaoanu** [comment]
New commit.

**Comment by lbargaoanu** [comment]
I can see why no more #if in TypeExtensions, but now what? :) Check by name, a new attribute?

**Comment by jbogard** [comment]
Nah, just remove the alternate. I'm moving to the .NET Platform stuff, which forces me to remove support for older platforms (Silverlight 4 etc), and DataAnnotations are just available. I'm trying to get rid of most of the conditional compilation stuff.

**Comment by lbargaoanu** [comment]
I think ComplexTypeAttribute is only in .NET 4.5.

**Comment by lbargaoanu** [comment]
Or maybe not :)

**Comment by lbargaoanu** [comment]
I'm not sure how useful this is. Complex types are usually configured in code I imagine, not with attributes (that's how I would do it). It doesn't help with #1001. There might be other similar situations.

**Comment by lbargaoanu** [comment]
Maybe reuse RequiredAttribute for #1001?

**Pull request closed without merging**
