### PR TITLE
Automate updating last version binary

### PR DESCRIPTION
**Pull request by lbargaoanu**
@jbogard I guess what's missing here is authentication, like [this](https://www.appveyor.com/docs/how-to/git-push/). So it makes sense only on merge. Thoughts?

### CODE REVIEW

**Comment by jbogard** [comment]
I think we can do all this via command line? The dotnet cli lets us create a project and add a Nuget package reference and build.

**Comment by jbogard** [comment]
Then we wouldn’t need to commit the binary at all, it could just grab the package from NuGet.

**Comment by lbargaoanu** [comment]
But then we still need some version of the binary in the repo for things to work locally. And the results would be different than on CI. A little weird. I'll give it a shot.

**Comment by lbargaoanu** [comment]
I think the best way would be using nuget.exe in a prebuild action. It works the same locally and on CI and it doesn't require the binary in source control. But it needs some logic. 9.0 would be compared with 8.0 and 8.1 also with 8.0. I started with some bat files and that didn't work out :) I guess is takes some PowerShell skills.

**Comment by Tasteful** [comment]
You can query the git for the tags and from that figure our the last version to check with.
```
$version_tags = (git tag -l) | Where-Object { $_ -match "^v\d+\.\d+\.\d+$" } | Sort-Object { [Version]$_ };
```

**Comment by lbargaoanu** [comment]
The logic is simple enough, but try writing that in a batch file :) That's why I think PowerShell is needed.

	if(version.Minor == 0 && version.Build == 0){
		var newVersion = new Version(version.Major - 1, 0, 0).Dump();
	}else{
		var newVersion = new Version(version.Major, 0, 0).Dump();
	}

**Pull request closed without merging**
