### PR TITLE
Global configuration

### PR DESCRIPTION
**Pull request by jbogard**
See #1796 for more information

### CODE REVIEW

**Comment by jbogard** [comment]
@TylerCarlson1 @lbargaoanu this adds the ProfileMap companion to TypeMap and PropertyMap. I'm not sure how I missed this one in the config overhaul, but it was quite a bit harder to break apart than the others.

**Comment by lbargaoanu** [comment]
That's a lot :) And it makes configuration more complex. But it makes sense.

**Comment by jbogard** [comment]
Yeah, it definitely adds more classes. I think this makes it consistent with the rest of the config API - you have config gatherers:

- Profile : IProfileExpression, IProfileConfiguration
- MappingExpression : IMappingExpression, ITypeMapConfiguration
- MemberConfigurationExpression : IMemberConfigurationExpression, IMemberConfiguration

Then configuration holders:

- ProfileMap
- TypeMap
- PropertyMap

And a very explicit boundary - MapperConfiguration can create the root ProfileMap and sub profiles. ProfileMap can create type maps, TypeMaps can create PropertyMaps, delegating to the IXyzConfiguration to fill in the details. Finally something that reads these configuration models to build the plan of execution.

More moving pieces but hopefully it helps bring the Profile class more consistent with the rest of the config API.

**Comment by TylerCarlson1** [comment]
My main concern is does mapper configuration conventions add on with sub profile's mapping.  Like if in a sub profile I want to remove flattening or other default member conventions, for whatever reasoning when mapping properties, and I have it in the mapping configuration, will that re-add it back into the sub profile?

As far as I can tell it doesn't look like it, but I haven't looked over the code extensively.

**Comment by jbogard** [comment]
No, I left the conventions alone as they currently are. You'd want to be able to add/remove them, so for everything you do in the root config, you'd want to undo in a profile.

**Pull request merged**
